import {useState} from 'react';
import './Capital.css';
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
const chapters=['Thesis','Assumption','Consequence','Capital','Horizon'];
export default function Capital(){const[units,setUnits]=useState(800),[chapter,setChapter]=useState(0);const price=180,cost=units>=1200?85:95,revenue=units*price,cogs=units*cost,gross=revenue-cogs,opex=45000+Math.max(0,units-1000)*15,profit=gross-opex,inventory=cogs*2,buffer=Math.max(0,-profit)*6,required=240000+inventory+buffer,available=1200000-240000-inventory,runway=profit<0?available/-profit:null;const ratio=units/2400,breakEven=530;const position=14+ratio*65;return <main id="study" className="capital-study" style={{'--mass':ratio} as React.CSSProperties}><header><a href="/capability-lab">DWS / CAPITAL INTELLIGENCE</a><span>07 / DEMONSTRATIVE MODEL</span></header><div className="capital-mast"><h1>CAPITAL</h1><p>One assumption.<br/><em>Every consequence.</em></p></div><nav aria-label="Investment thesis chapters">{chapters.map((s,i)=><button key={s} aria-pressed={chapter===i} onClick={()=>setChapter(i)}>0{i+1} <span>{s}</span></button>)}</nav><section className="capital-document" aria-label={chapters[chapter]}>
 <div className="capital-thesis"><span>THE BUSINESS THESIS</span><h2>A useful object.<br/>{' '}A repeatable<br/>{' '}<em>economy.</em></h2><p>Fictional direct-to-customer product.<br/>One price. One volume assumption.<br/>Every dependency exposed.</p><dl><div><dt>UNIT PRICE</dt><dd>$180</dd></div><div><dt>UNIT COST</dt><dd>${cost}</dd></div><div><dt>GROSS MARGIN</dt><dd>{(gross/revenue*100).toFixed(1)}%</dd></div></dl></div>
 <div className="capital-gravity"><div className="capital-revenue" style={{left:6+ratio*12+'%'}}><span>MONTHLY REVENUE</span><strong style={{fontSize:`clamp(48px,${6+ratio*3}vw,145px)`}}>{money(revenue)}</strong></div><svg viewBox="0 0 1000 430" role="img" aria-label={`Revenue ${money(revenue)}, cost of goods ${money(cogs)}, operating cost ${money(opex)}, monthly operating result ${money(profit)}`}><line x1="30" y1="285" x2="960" y2="285" stroke="currentColor" opacity=".3"/><path d={`M30 270L${80+ratio*80} ${220-ratio*180}H${420+ratio*540}V270Z`} fill="#294937"/><path d={`M30 285H${70+cogs/revenue*800}V${315+cogs/240000*55}H30Z`} fill="#b3aa8d"/><path d={`M${85+cogs/revenue*800} 285H960V${315+opex/80000*55}H${85+cogs/revenue*800}Z`} fill="#d1c7ad"/><line x1={position*10} y1="20" x2={position*10} y2="410" stroke="#728371" strokeDasharray="3 7"/><text x="40" y="410" fontSize="14" fill="currentColor">COST OF GOODS</text><text x="800" y="410" fontSize="14" fill="currentColor">OPERATIONS</text></svg><div className="capital-result" style={{marginLeft:Math.max(0,ratio*30)+'%'}}><span>MONTHLY OPERATING RESULT</span><strong>{profit<0?'−':'+'}{money(Math.abs(profit))}</strong><p>{profit<0?'The thesis needs a funded path to demand.':'Volume clears the operating threshold.'}</p></div></div>
 </section><section className="capital-footnote" aria-live="polite">{chapter===3?<><h2>Capital has<br/><em>a destination.</em></h2><div className="capital-allocation">{[['Formation + tooling',240000],['Two-month inventory',inventory],['Six-month loss reserve',buffer]].map(([name,value])=><div key={name} style={{flexGrow:Number(value)||.01}}><b>{money(Number(value))}</b><span>{name}</span></div>)}<p>Required initial capital <strong>{money(required)}</strong> · Demonstrative funding envelope $1.2m</p></div></>:chapter===4?<><h2>The next<br/><em>operating state.</em></h2><div className="capital-horizon"><div style={{width:30+ratio*60+'%'}}><span>SETUP → FIRST DELIVERY → OPERATING THRESHOLD</span><strong>{units>=breakEven?'Threshold reached at selected volume.':`${breakEven-units} more units / month to threshold.`}</strong></div><p>{runway?`${runway.toFixed(1)} months modeled cash runway at constant monthly loss.`:'No recurring cash burn in this static scenario.'} Annualized operating result / required initial capital: {(profit*12/required*100).toFixed(1)}%. This is an operating ratio, not an investor return.</p></div></>:<><h2>{chapter===1?'Move the premise.':chapter===2?'Watch the weight shift.':'The model is the argument.'}</h2><p>Cost reduces from $95 to $85 at 1,200 units. Monthly operating cost starts at $45,000, adding $15 per unit above 1,000. Setup is $240,000. Cash timing, tax, debt, growth and returns are outside this illustration.</p></>}</section><footer><label><span>MASTER ASSUMPTION / MONTHLY UNIT VOLUME <b>{units.toLocaleString()}</b></span><input type="range" min="200" max="2400" step="10" value={units} aria-label="Monthly unit volume" onFocus={()=>setChapter(1)} onChange={e=>{setUnits(+e.target.value);setChapter(2)}}/><small>200 UNITS <i/> 2,400 UNITS</small></label><p>FICTIONAL DATA / USD<br/>A causal model. No company claims or investment forecast.</p></footer></main>}


