import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
export default function NativeScene({kind,value=0,material=false,section=false}:{kind:'object'|'space';value?:number;material?:boolean;section?:boolean}){
 const host=useRef<HTMLDivElement>(null),update=useRef<(v:number,m:boolean,s:boolean)=>void>(()=>{});const[failed,setFailed]=useState(false);
 useEffect(()=>{const el=host.current!;let r:T.WebGLRenderer;try{r=new T.WebGLRenderer({antialias:true,alpha:true})}catch{setFailed(true);return}let disposed=false,frame=0;const scene=new T.Scene();const camera=new T.PerspectiveCamera(kind==='object'?34:53,1,.01,100);r.setPixelRatio(Math.min(devicePixelRatio,1.6));r.setClearColor(kind==='object'?'#15191a':'#b5b09f',1);r.shadowMap.enabled=true;r.shadowMap.type=T.PCFSoftShadowMap;r.toneMapping=T.ACESFilmicToneMapping;r.toneMappingExposure=kind==='object'?1.35:1.05;el.appendChild(r.domElement);const pm=new T.PMREMGenerator(r),room=new RoomEnvironment(),env=pm.fromScene(room,.04);scene.environment=env.texture;scene.environmentIntensity=kind==='object'?.55:.3;room.dispose();pm.dispose();
 const metal=new T.MeshStandardMaterial({color:'#b7b4a8',metalness:.85,roughness:.28}),ceramic=new T.MeshStandardMaterial({color:'#ded2b7',roughness:.48}),dark=new T.MeshStandardMaterial({color:'#232626',metalness:.7,roughness:.3}),stone=new T.MeshStandardMaterial({color:'#c7bfaa',roughness:.88}),warm=new T.MeshStandardMaterial({color:'#9f6b42',roughness:.72}),signal=new T.MeshStandardMaterial({color:'#315eff',emissive:'#173acb',emissiveIntensity:.5});const mats=[metal,ceramic,dark,stone,warm,signal];const geos:T.BufferGeometry[]=[];const group=new T.Group();scene.add(group);const parts:T.Mesh[]=[];
 function mesh(g:T.BufferGeometry,m:T.Material,x=0,y=0,z=0,parent:T.Object3D=group){geos.push(g);const a=new T.Mesh(g,m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;parent.add(a);return a}
 function box(w:number,h:number,d:number,m:T.Material,x:number,y:number,z:number,parent:T.Object3D=group){return mesh(new T.BoxGeometry(w,h,d),m,x,y,z,parent)}
 let controls:OrbitControls|undefined;
 if(kind==='object'){
 const arch=new T.Shape();arch.moveTo(-1.12,0);arch.lineTo(-1.12,1.18);arch.absarc(0,1.18,1.12,Math.PI,0,true);arch.lineTo(1.12,0);arch.lineTo(.79,0);arch.lineTo(.79,1.18);arch.absarc(0,1.18,.79,0,Math.PI,false);arch.lineTo(-.79,0);arch.closePath();
 for(let i=0;i<15;i++){const fin=mesh(new T.ExtrudeGeometry(arch,{depth:.045,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.016,bevelThickness:.012,curveSegments:64}),metal,0,.15,(i-7)*.071);parts.push(fin)}
 const core=mesh(new T.ExtrudeGeometry(arch,{depth:.32,bevelEnabled:true,bevelSegments:4,bevelSize:.035,bevelThickness:.03,curveSegments:64}),ceramic,0,.15,-.16);core.scale.set(.96,.96,1);for(const x of [-.94,.94]){box(.42,.15,1.2,dark,x,.075,0);for(let i=0;i<7;i++)box(.006,.04,.8,metal,x-.12+i*.04,.154,0)}box(.075,.009,.27,signal,.94,.158,.29);for(const x of [-.94,.94])box(.12,1.13,.13,dark,x,.7,0);
 group.rotation.y=-.35;camera.position.set(3.6,2.9,5.5);camera.lookAt(0,1.1,0);controls=new OrbitControls(camera,r.domElement);controls.target.set(0,1.1,0);controls.enablePan=false;controls.enableZoom=false;controls.minPolarAngle=.5;controls.maxPolarAngle=1.55;controls.update();
 const floor=mesh(new T.PlaneGeometry(200,200),new T.ShadowMaterial({opacity:.32}),0,-.018,0,scene);floor.rotation.x=-Math.PI/2;const oldDispose= floor.geometry.dispose.bind(floor.geometry);floor.geometry.dispose=()=>{(floor.material as T.Material).dispose();oldDispose()};
 }else{
 scene.fog=new T.Fog('#b5b09f',14,39);camera.position.set(0,2.8,9);camera.lookAt(0,2,-8);box(45,.3,70,stone,0,-.15,-15);box(3,.25,46,stone,-6,6,-13);box(3,.25,46,stone,6,6,-13);for(let i=0;i<9;i++){const z=4-i*4;box(.45,6,.7,stone,-5,3,z);box(.45,6,.7,stone,5,3,z);box(10.4,.35,.7,stone,0,5.82,z)}box(.3,7,60,warm,-7,3,-15);box(.3,7,60,stone,7,3,-15);
 for(let i=0;i<10;i++){const pivot=new T.Group();pivot.position.set(-4.5+i,0,1);group.add(pivot);const panel=box(.86,5.3,.2,i%2?stone:warm,0,2.65,0,pivot);parts.push(panel)}
 box(8,4,.4,warm,0,2,-27);box(2.8,4.8,.3,dark,0,2.4,-26.7);const pool=box(3.2,.018,13,new T.MeshStandardMaterial({color:'#526866',metalness:.55,roughness:.2}),0,.012,-12);mats.push(pool.material as T.MeshStandardMaterial);
 }
 scene.add(new T.HemisphereLight('#e9e4d8','#242a2b',kind==='object'?1.4:1));const key=new T.DirectionalLight('#fff0d7',kind==='object'?2.6:4.2);key.position.set(-4,8,5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-12;key.shadow.camera.right=12;key.shadow.camera.top=12;key.shadow.camera.bottom=-12;key.shadow.normalBias=.025;scene.add(key);const rim=new T.DirectionalLight('#d8e6f2',2.3);rim.position.set(4,4,-4);scene.add(rim);
 let current=0,target=0;const draw=()=>{if(disposed)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;current=reduced?target:current+(target-current)*.12;if(kind==='object'){parts.forEach((p,i)=>{p.position.z=(i-7)*(.071+current*.065);p.visible=!section||i<7});}else{parts.forEach((p,i)=>{p.parent!.rotation.y=(.22+current*1.25)*(i%2?1:-1)});camera.position.z=9-current*10;camera.position.x=current*.8;camera.lookAt(0,2,-8)}r.render(scene,camera);if(Math.abs(target-current)>.001)frame=requestAnimationFrame(draw)};
 update.current=(v,m,s)=>{target=v;metal.color.set(m?'#444d4f':'#b7b4a8');metal.roughness=m?.43:.28;if(kind==='object')parts.forEach((p,i)=>p.visible=!s||i<7);cancelAnimationFrame(frame);/* section visibility persists through assembly interpolation */section=s;draw()};const resize=()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();r.setSize(el.clientWidth,el.clientHeight);draw()};const ro=new ResizeObserver(resize);ro.observe(el);controls?.addEventListener('change',draw);resize();const loss=(e:Event)=>{e.preventDefault();setFailed(true)};r.domElement.addEventListener('webglcontextlost',loss);
 return()=>{disposed=true;cancelAnimationFrame(frame);ro.disconnect();controls?.dispose();r.domElement.removeEventListener('webglcontextlost',loss);geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());env.dispose();r.dispose();r.domElement.remove()};
 // Scene topology is created once; subsequent changes use the retained update function.

 },[kind]);useEffect(()=>update.current(value,material,section),[value,material,section]);return <div className={'native-scene native-'+kind} ref={host} role="img" aria-label={kind==='object'?'Dimensional modular radiant arch, with machined fins and ceramic inner core':'Architectural passage with pivoting stone screens, colonnade and reflecting channel'}>{failed&&<p className="native-unavailable">This dimensional study requires WebGL. Please open it in a supported browser.</p>}</div>
}



