import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import {RoundedBoxGeometry} from 'three/examples/jsm/geometries/RoundedBoxGeometry.js';
import {RectAreaLightUniformsLib} from 'three/examples/jsm/lights/RectAreaLightUniformsLib.js';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
export default function NativeScene({kind,value=0,material=0,section=false}:{kind:'object'|'space';value?:number;material?:number;section?:boolean}){
 const host=useRef<HTMLDivElement>(null),update=useRef<(v:number,m:number,s:boolean)=>void>(()=>{});const[failed,setFailed]=useState(false);
 useEffect(()=>{const el=host.current!;let r:T.WebGLRenderer;try{r=new T.WebGLRenderer({antialias:true,alpha:true})}catch{setFailed(true);return}let disposed=false,frame=0;const scene=new T.Scene();const camera=new T.PerspectiveCamera(kind==='object'?34:53,1,.01,100);r.setPixelRatio(Math.min(devicePixelRatio,1.6));r.setClearColor(kind==='object'?'#15191a':'#b5b09f',1);r.shadowMap.enabled=true;r.shadowMap.type=T.PCFSoftShadowMap;r.toneMapping=T.ACESFilmicToneMapping;r.toneMappingExposure=kind==='object'?1.35:1.05;el.appendChild(r.domElement);const pm=new T.PMREMGenerator(r),room=new RoomEnvironment(),env=pm.fromScene(room,.04);scene.environment=env.texture;scene.environmentIntensity=kind==='object'?.55:.3;room.dispose();pm.dispose();
 const metal=new T.MeshStandardMaterial({color:'#b7b4a8',metalness:.85,roughness:.28}),ceramic=new T.MeshStandardMaterial({color:'#ded2b7',roughness:.48}),dark=new T.MeshStandardMaterial({color:'#232626',metalness:.7,roughness:.3}),stone=new T.MeshStandardMaterial({color:'#c7bfaa',roughness:.88}),warm=new T.MeshStandardMaterial({color:'#9f6b42',roughness:.72}),signal=new T.MeshStandardMaterial({color:'#315eff',emissive:'#173acb',emissiveIntensity:.5});const textures:T.Texture[]=[];
 const grain=document.createElement('canvas');grain.width=grain.height=256;const ctx=grain.getContext('2d')!;const pixels=ctx.createImageData(256,256);let seed=17;for(let i=0;i<pixels.data.length;i+=4){seed=(seed*1664525+1013904223)>>>0;const v=120+(seed%32);pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=v;pixels.data[i+3]=255}ctx.putImageData(pixels,0,0);const micro=new T.CanvasTexture(grain);micro.wrapS=micro.wrapT=T.RepeatWrapping;micro.repeat.set(18,18);textures.push(micro);metal.bumpMap=micro;metal.bumpScale=.0008;metal.roughnessMap=micro;stone.bumpMap=micro;stone.bumpScale=.012;warm.bumpMap=micro;warm.bumpScale=.008;ceramic.bumpMap=micro;ceramic.bumpScale=.001;
 const glass=new T.MeshPhysicalMaterial({color:'#7b8e86',metalness:.15,roughness:.19,transparent:true,opacity:.24,side:T.DoubleSide,depthWrite:false});
 const mats=[glass,metal,ceramic,dark,stone,warm,signal];const geos:T.BufferGeometry[]=[];const group=new T.Group();scene.add(group);const parts:T.Mesh[]=[];
 function mesh(g:T.BufferGeometry,m:T.Material,x=0,y=0,z=0,parent:T.Object3D=group){geos.push(g);const a=new T.Mesh(g,m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;parent.add(a);return a}
 function box(w:number,h:number,d:number,m:T.Material,x:number,y:number,z:number,parent:T.Object3D=group){return mesh(new RoundedBoxGeometry(w,h,d,2,Math.min(w,h,d)*.045),m,x,y,z,parent)}
 function lettering(lines:string[],w:number,h:number,x:number,y:number,z:number,parent:T.Object3D=group){const c=document.createElement('canvas');c.width=2048;c.height=1024;const a=c.getContext('2d')!;a.fillStyle=lines[0].includes('A SPATIAL')?'#303431':'#eee7d8';a.textBaseline='top';lines.forEach((line,i)=>{a.font=i===0?'34px Arial':'270px Georgia';a.fillText(line,80,40+i*295)});const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;textures.push(t);const m=new T.MeshBasicMaterial({map:t,transparent:true,side:T.FrontSide,depthWrite:false,alphaTest:.05});mats.push(m as unknown as T.MeshStandardMaterial);const label=mesh(new T.PlaneGeometry(w,h),m,x,y,z,parent);label.castShadow=false;label.receiveShadow=false;return label}
 let controls:OrbitControls|undefined;
 if(kind==='object'){
 const arch=new T.Shape();arch.moveTo(-1.12,0);arch.lineTo(-1.12,1.18);arch.absarc(0,1.18,1.12,Math.PI,0,true);arch.lineTo(1.12,0);arch.lineTo(.79,0);arch.lineTo(.79,1.18);arch.absarc(0,1.18,.79,0,Math.PI,false);arch.lineTo(-.79,0);arch.closePath();
 for(let i=0;i<15;i++){const fin=mesh(new T.ExtrudeGeometry(arch,{depth:.045,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.016,bevelThickness:.012,curveSegments:64}),metal,0,.15,(i-7)*.071);fin.scale.y=1+(i%3-1)*.0006;parts.push(fin)}
 const core=mesh(new T.ExtrudeGeometry(arch,{depth:.32,bevelEnabled:true,bevelSegments:4,bevelSize:.035,bevelThickness:.03,curveSegments:64}),ceramic,0,.15,-.16);core.scale.set(.96,.96,1);for(const x of [-.94,.94]){box(.42,.15,1.2,dark,x,.075,0);for(let i=0;i<7;i++)box(.006,.04,.8,metal,x-.12+i*.04,.154,0)}box(.075,.009,.27,signal,.94,.158,.29);for(const x of [-.94,.94])box(.12,1.13,.13,dark,x,.7,0);
 for(const x of [-.94,.94]){for(const y of [.25,1.05]){const rod=mesh(new T.CylinderGeometry(.018,.018,1.02,24),dark,x,y,0);rod.rotation.x=Math.PI/2;for(const z of [-.56,.56]){const screw=mesh(new T.CylinderGeometry(.033,.033,.028,6),metal,x,y,z);screw.rotation.x=Math.PI/2;box(.036,.006,.003,dark,x,y,z+(z>0?.018:-.018))}}}for(let i=0;i<10;i++)box(.025,.75,.02,ceramic,-.97+i*.007,.7,0);
 group.rotation.y=-.35;camera.position.set(3.6,2.9,5.5);camera.lookAt(0,1.1,0);controls=new OrbitControls(camera,r.domElement);controls.target.set(0,1.1,0);controls.enablePan=false;controls.enableZoom=false;controls.minPolarAngle=.5;controls.maxPolarAngle=1.55;controls.update();
 const floor=mesh(new T.PlaneGeometry(200,200),new T.ShadowMaterial({opacity:.32}),0,-.018,0,scene);floor.rotation.x=-Math.PI/2;const oldDispose= floor.geometry.dispose.bind(floor.geometry);floor.geometry.dispose=()=>{(floor.material as T.Material).dispose();oldDispose()};
 }else{
 scene.fog=new T.Fog('#b5b09f',14,39);camera.position.set(0,2.8,9);camera.lookAt(0,2,-8);box(45,.3,70,stone,0,-.15,-15);box(3,.25,46,stone,-6,6,-13);box(3,.25,46,stone,6,6,-13);for(let i=0;i<9;i++){const z=4-i*4;box(.45,6,.7,stone,-5,3,z);box(.45,6,.7,stone,5,3,z);box(10.4,.35,.7,stone,0,5.82,z)}box(.3,7,60,warm,-7,3,-15);box(.3,7,60,stone,7,3,-15);
 for(let i=0;i<2;i++){const pivot=new T.Group();pivot.position.set(i?2.05:-2.05,0,1);group.add(pivot);const panel=box(4,5.3,.42,i?dark:stone,0,2.65,0,pivot);parts.push(panel);lettering(i?['02 / THE INNER WORLD','Room','to be.']:['01 / A SPATIAL EXPERIENCE','Somewhere','within.'],3.8,2.1,0,3,.225,pivot);box(.04,4.8,.02,metal,i?-1.8:1.8,2.65,.23,pivot)}
 for(const z of [-8,-15]){box(.16,4.6,2.8,dark,-3.7,2.3,z);const pane=box(3.4,3.6,.06,glass,4.6,2.5,z);pane.rotation.y=-.16;lettering(z===-8?['01 / THE EXPERIENCE','Light. Space.','Stillness.']:['02 / THE MATERIAL','Stone, softened.','Time, slowed.'],2.3,1.5,4.4,2.9,z+.08)}
 lettering(['THE INNER COURT','A place','to arrive.'],5,2.5,0,3,-22);box(5.5,4,.2,dark,0,2.7,-22.1);box(.18,5,.35,metal,-3.4,2.5,-23);box(.18,5,.35,metal,3.4,2.5,-23);box(7,.18,.35,metal,0,5,-23);

 box(8,4,.4,warm,0,2,-27);box(2.8,4.8,.3,dark,0,2.4,-26.7);const pool=box(3.2,.018,13,new T.MeshStandardMaterial({color:'#526866',metalness:.55,roughness:.2}),0,.012,-12);mats.push(pool.material as T.MeshStandardMaterial);
 }
 RectAreaLightUniformsLib.init();const soft=new T.RectAreaLight('#fff0df',kind==='object'?5:3,5,7);soft.position.set(-3,4,4);soft.lookAt(0,1,0);scene.add(soft);const fill=new T.RectAreaLight('#ced9e1',2,3,5);fill.position.set(4,2,-2);fill.lookAt(0,1,0);scene.add(fill);
 scene.add(new T.HemisphereLight('#e9e4d8','#242a2b',kind==='object'?1.4:1));const key=new T.DirectionalLight('#fff0d7',kind==='object'?1.3:3.2);key.position.set(-4,8,5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-12;key.shadow.camera.right=12;key.shadow.camera.top=12;key.shadow.camera.bottom=-12;key.shadow.normalBias=.003;key.shadow.radius=4;key.shadow.camera.left=kind==='object'?-3:-12;key.shadow.camera.right=kind==='object'?3:12;key.shadow.camera.top=kind==='object'?4:12;key.shadow.camera.bottom=kind==='object'?-1:-12;scene.add(key);const rim=new T.DirectionalLight('#d8e6f2',2.3);rim.position.set(4,4,-4);scene.add(rim);
 let current=0,target=0;const draw=()=>{if(disposed)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;current=reduced?target:current+(target-current)*.12;if(kind==='object'){parts.forEach((p,i)=>{p.position.z=(i-7)*(.071+current*.065);p.visible=!section||i<7});}else{parts.forEach((p,i)=>{p.parent!.rotation.y=(current*1.38)*(i%2?1:-1)});camera.position.z=9-current*21;camera.position.x=innerWidth<600?-2.05*(1-current)-.45:current*.8;camera.lookAt(innerWidth<600?-2.05*(1-current)-.45:0,2,-8-current*18)}r.render(scene,camera);if(Math.abs(target-current)>.001)frame=requestAnimationFrame(draw)};
 update.current=(v,m,s)=>{target=v;metal.color.set(['#b7b4a8','#15191c','#b5a38a'][m]);metal.metalness=m===0?.78:m===1?.12:.04;metal.roughness=m===0?.48:m===1?.36:.8;metal.bumpScale=m===2?.003:.0008;if(kind==='object')parts.forEach((p,i)=>p.visible=!s||i<7);cancelAnimationFrame(frame);/* section visibility persists through assembly interpolation */section=s;draw()};const resize=()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();r.setSize(el.clientWidth,el.clientHeight);draw()};const ro=new ResizeObserver(resize);ro.observe(el);controls?.addEventListener('change',draw);resize();const loss=(e:Event)=>{e.preventDefault();setFailed(true)};r.domElement.addEventListener('webglcontextlost',loss);
 return()=>{disposed=true;cancelAnimationFrame(frame);ro.disconnect();controls?.dispose();r.domElement.removeEventListener('webglcontextlost',loss);geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());env.dispose();r.dispose();r.domElement.remove()};
 // Scene topology is created once; subsequent changes use the retained update function.

 },[kind]);useEffect(()=>update.current(value,material,section),[value,material,section]);return <div className={'native-scene native-'+kind} ref={host} role="img" aria-label={kind==='object'?'Dimensional modular radiant arch, with machined fins and ceramic inner core':'Architectural passage with pivoting stone screens, colonnade and reflecting channel'}>{failed&&<p className="native-unavailable">This dimensional study requires WebGL. Please open it in a supported browser.</p>}</div>
}







