import {useEffect,useRef,useState} from 'react';
import './Orchestration.css';
const stages=['Ingest','Classify','Route','Execute','Human gate','Validate','Publish','Audit'];
type Status='idle'|'running'|'gate'|'exception'|'complete'|'rejected';
export default function Orchestration(){const started=useRef(0);const[step,setStep]=useState(-1),[status,setStatus]=useState<Status>('idle'),[exception,setException]=useState(true),[retried,setRetried]=useState(false),[events,setEvents]=useState<string[]>([]),[run,setRun]=useState(0);const log=(s:string)=>setEvents(e=>[...e,`${((performance.now()-started.current)/1000).toFixed(1)}s / ${s}`]);
 useEffect(()=>{if(status!=='running')return;const timer=setTimeout(()=>{if(step===3){setStep(4);setStatus('gate');setEvents(e=>[...e,`${((performance.now()-started.current)/1000).toFixed(1)}s / Human authorization required. Downstream held.`])}else if(step===5&&exception&&!retried){setStatus('exception');setEvents(e=>[...e,`${((performance.now()-started.current)/1000).toFixed(1)}s / Checksum mismatch. Output isolated. Publish blocked.`])}else if(step===7){setStatus('complete');setEvents(e=>[...e,`${((performance.now()-started.current)/1000).toFixed(1)}s / Audit sealed. Simulation complete.`])}else{setStep(s=>s+1);setEvents(e=>[...e,`${((performance.now()-started.current)/1000).toFixed(1)}s / ${stages[step+1]} entered.`])}},step===3?1800:1100);return()=>clearTimeout(timer)},[step,status,exception,retried]);
 function start(){started.current=performance.now();setRun(r=>r+1);setStep(0);setStatus('running');setRetried(false);setEvents(['00 / Fictional brief received. No external systems connected.'])}const title=status==='idle'?'A chain of intelligence.':status==='gate'?'Your judgment.':status==='exception'?'Contained.':status==='complete'?'Accounted for.':status==='rejected'?'Stopped by you.':stages[step]+'.';
 return <main id="study" className="orchestration" data-state={status}><header><a href="/capability-lab">DWS / EXECUTION INTELLIGENCE</a><span>08 / LOCAL SIMULATION</span></header><div className="orchestra-title"><h1>ORCHESTRATION</h1><p>One input.<br/>A chain of intelligence.</p></div><section className="orchestra-field" aria-label="Temporal execution field"><div className="orchestra-clock"><span>RUN / {String(run).padStart(3,'0')}</span><strong>{step<0?'—':String(step+1).padStart(2,'0')}</strong><small>{status.toUpperCase()}</small></div><div className="orchestra-current" role="status" aria-live="polite"><p>{status==='gate'?'EXECUTION HELD / NOTHING PUBLISHES WITHOUT YOU':status==='exception'?'VALIDATION FAILED / OUTPUT QUARANTINED':'SIMULATED CAMPAIGN BRIEF → VALIDATED LOCAL OUTPUT'}</p><h2>{title}</h2><div className="orchestra-actions">{status==='gate'?<><button onClick={()=>{log('04 / Approved by reviewer.');setStep(5);setStatus('running')}}>Approve →</button><button onClick={()=>{log('04 / Returned for reclassification.');setStep(1);setStatus('running')}}>Return ↶</button><button onClick={()=>{log('04 / Rejected by reviewer. Run closed without publication.');setStatus('rejected')}}>Reject ×</button></>:status==='exception'?<><p>Checksum mismatch in the simulated output.<br/>Publication remains blocked.</p><button onClick={()=>{setRetried(true);log('05 / Repair applied. Validation retry requested.');setStatus('running')}}>Repair + retry →</button></>:status==='complete'?<p>One authorized output. Eight traceable stages.<br/>All activity remained in this browser.</p>:status==='running'&&step===3?<div className="orchestra-parallel"><span>COPY / RESOLVING</span><span>FORMAT / RESOLVING</span><span>POLICY / CHECKING</span></div>:<p>{status==='idle'?'The run will stop at a human gate. You decide what follows.':status==='rejected'?'No output published. Rejection recorded in the audit.':'Transforming the brief. Carrying its history forward.'}</p>}</div></div>
 <div className="execution-axis" role="list" aria-label="Execution stages">{stages.map((s,i)=><div key={s} role="listitem" className={step===i?'current':step>i||status==='complete'?'done':'waiting'}><span>{String(i+1).padStart(2,'0')}</span><i aria-hidden="true"/><strong>{s}</strong><small>{step===i?status==='gate'?'HELD':status==='exception'?'ISOLATED':status==='complete'?'SEALED':status==='rejected'?'CLOSED':'ACTIVE':step>i||status==='complete'?'COMPLETE':'WAITING'}</small></div>)}</div></section><footer><div className="orchestra-run"><button onClick={start} disabled={['running','gate','exception'].includes(status)}>{status==='idle'?'Run job →':'Run again →'}</button><label><input type="checkbox" checked={exception} disabled={['running','gate','exception'].includes(status)} onChange={e=>setException(e.target.checked)}/> Simulate one validation exception</label></div><div className="orchestra-log"><span>AUDIT / {events.length} EVENTS</span><ol aria-label="Run audit">{events.slice(-4).map((e,i)=><li key={events.length-4+i}>{e}</li>)}</ol></div><p>No agents, integrations or services connected.<br/>Execution and publication are demonstrative.</p></footer></main>
}

