import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
type Props={progress:number;material:number;finish:number;reveal:number};
const clamp=(n:number)=>Math.min(1,Math.max(0,n));
export default function PackagingScene(props:Props){
 const host=useRef<HTMLDivElement>(null),update=useRef<(v:Props)=>void>(()=>{}),initial=useRef(props);const[failed,setFailed]=useState(false);
 useEffect(()=>{const el=host.current!;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:true})}catch{setFailed(true);return}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.VSMShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;el.appendChild(renderer.domElement);
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(34,1,.1,100);const pm=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pm.fromScene(room,.04);scene.environment=env.texture;scene.environmentIntensity=.32;room.dispose();pm.dispose();
 const grain=document.createElement('canvas');grain.width=grain.height=256;const ctx=grain.getContext('2d')!,data=ctx.createImageData(256,256);let random=123;for(let i=0;i<data.data.length;i+=4){random=(random*1664525+1013904223)>>>0;const value=130+(random%80);data.data[i]=data.data[i+1]=data.data[i+2]=value;data.data[i+3]=255}ctx.putImageData(data,0,0);const texture=new T.CanvasTexture(grain);texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.repeat.set(3,3);
 const stock=new T.MeshStandardMaterial({color:'#c8bda6',roughness:.87,bumpMap:texture,bumpScale:.018}),edge=new T.MeshStandardMaterial({color:'#978a73',roughness:.97}),inner=new T.MeshStandardMaterial({color:'#aea18b',roughness:.95,bumpMap:texture,bumpScale:.012}),ink=new T.LineBasicMaterial({color:'#80655b',transparent:true,opacity:.5}),scoreMat=new T.MeshStandardMaterial({color:'#9d8d75',roughness:.95});const geometries:T.BufferGeometry[]=[],materials:T.Material[]=[stock,edge,inner,ink,scoreMat];
 const root=new T.Group();root.rotation.y=.2;scene.add(root);
 const shape=(points:number[][])=>{const s=new T.Shape();points.forEach(([x,z],i)=>i?s.lineTo(x,-z):s.moveTo(x,-z));s.closePath();return s};
 const hex=(r:number)=>shape(Array.from({length:6},(_,i)=>[Math.sin(Math.PI/6+i*Math.PI/3)*r,Math.cos(Math.PI/6+i*Math.PI/3)*r]));
 const rect=(x:number,z:number,w:number,h:number)=>new T.Path([new T.Vector2(x,-z),new T.Vector2(x+w,-z),new T.Vector2(x+w,-z-h),new T.Vector2(x,-z-h),new T.Vector2(x,-z)]);
 function board(s:T.Shape,parent:T.Object3D,mat:T.Material=stock,thick=.025){const g=new T.ExtrudeGeometry(s,{depth:thick,bevelEnabled:true,bevelSize:.006,bevelThickness:.004,bevelSegments:2,steps:1,curveSegments:24});g.rotateX(-Math.PI/2);geometries.push(g);const mesh=new T.Mesh(g,[mat,edge]);mesh.castShadow=mesh.receiveShadow=true;parent.add(mesh);return mesh}
 function line(points:T.Vector3[],parent:T.Object3D){const g=new T.BufferGeometry().setFromPoints(points);geometries.push(g);const l=new T.Line(g,ink);parent.add(l);return l}
 function groove(length:number,parent:T.Object3D,z=0){const g=new T.CylinderGeometry(.009,.009,length,8);g.rotateZ(Math.PI/2);geometries.push(g);const m=new T.Mesh(g,scoreMat);m.position.set(0,.027,z);parent.add(m)}
 board(hex(1.5),root);const walls:T.Group[]=[],roofs:T.Group[]=[],tabs:T.Group[]=[],tails:T.Group[]=[],seams:T.Group[]=[];const annotations=new T.Group();root.add(annotations);const emboss=new T.Group(),registered=new T.Group();
 for(let i=0;i<6;i++){
  const angle=i*Math.PI/3,axis=new T.Group();axis.rotation.y=angle;axis.position.set(Math.sin(angle)*1.299,0,Math.cos(angle)*1.299);root.add(axis);const wall=new T.Group();axis.add(wall);walls.push(wall);board(shape([[-.75,0],[.75,0],[.75,.95],[-.75,.95]]),wall);groove(1.46,axis);groove(1.46,wall,.95);
  const roof=new T.Group();roof.position.z=.95;wall.add(roof);roofs.push(roof);board(shape([[-.75,0],[.75,0],[.27,.915],[-.27,.915]]),roof);
  const tab=new T.Group();tab.position.z=.915;roof.add(tab);tabs.push(tab);board(shape([[-.155,0],[.155,0],[.155,.10],[-.155,.10]]),tab);const tail=new T.Group();tail.position.z=.10;tab.add(tail);tails.push(tail);board(shape([[-.155,0],[.155,0],[.11,.09],[-.11,.09]]),tail);groove(.30,roof,.915);
  // Parallel inset/bleed lines and registration crosses belong to the flat blank only.
  const reg=new T.Group();axis.add(reg);reg.add(new T.Group());for(const d of [.04,-.035])line([new T.Vector3(-.75+d,.035,d),new T.Vector3(.75-d,.035,d),new T.Vector3(.75-d,.035,.95),new T.Vector3(.2-d,.035,1.83-d)],reg);
  line([new T.Vector3(-.84,.034,.38),new T.Vector3(-.74,.034,.38)],reg);line([new T.Vector3(-.79,.034,.33),new T.Vector3(-.79,.034,.43)],reg);annotations.add(reg);reg.position.copy(axis.position);reg.rotation.copy(axis.rotation);
  const side=new T.Group();side.position.set(.72,.05,.1);wall.add(side);seams.push(side);board(shape([[0,0],[.13,.06],[.13,.72],[0,.78]]),side,inner,.018);
 }
 // The fitted insert is a separate die-cut part: a hexagonal tray with a real circular cradle aperture.
 const tray=new T.Group();root.add(tray);const trayShape=hex(1.30);const hole=new T.Path();hole.absarc(0,0,.63,0,Math.PI*2,true);trayShape.holes.push(hole);board(trayShape,tray,inner,.035);
 for(let i=0;i<6;i++){const a=i*Math.PI/3;const leg=new T.Group();leg.position.set(Math.sin(a)*.94,-.35,Math.cos(a)*.94);leg.rotation.y=a;board(shape([[-.28,0],[.28,0],[.28,.32],[-.28,.32]]),leg,inner);leg.rotation.x=Math.PI/2;tray.add(leg)}
 const basin=new T.Mesh(new T.CylinderGeometry(.625,.55,.22,64,1,true),inner);geometries.push(basin.geometry);basin.position.y=-.11;basin.castShadow=basin.receiveShadow=true;tray.add(basin);const bottom=new T.Mesh(new T.CircleGeometry(.55,64),inner);geometries.push(bottom.geometry);bottom.rotation.x=-Math.PI/2;bottom.position.y=-.22;tray.add(bottom);
 // Slotted crown receives all six roof tongues; the reveal lifts it with the inner presentation carriage.
 const crown=new T.Group();root.add(crown);const crownShape=hex(.54);for(let i=0;i<6;i++){const a=i*Math.PI/3;const path=rect(-.17,.36,.34,.045);path.curves.forEach(curve=>{if(curve instanceof T.LineCurve){for(const point of [curve.v1,curve.v2]){const x=point.x,y=point.y;point.set(x*Math.cos(a)-y*Math.sin(a),x*Math.sin(a)+y*Math.cos(a))}}});crownShape.holes.push(path)}board(crownShape,crown,stock,.04);crown.add(emboss,registered);
 for(let i=0;i<3;i++){const strip=shape([[-.17+i*.11,-.18],[-.13+i*.11,-.18],[-.13+i*.11,.18],[-.17+i*.11,.18]]);const m=board(strip,emboss,stock,.003);m.position.y=.045}
 for(const z of [-.13,0,.13])line([new T.Vector3(-.2,.052,z),new T.Vector3(.2,.052,z)],registered);
 const floorGeo=new T.PlaneGeometry(30,30);geometries.push(floorGeo);const floorMat=new T.ShadowMaterial({opacity:.17});materials.push(floorMat);const floor=new T.Mesh(floorGeo,floorMat);floor.rotation.x=-Math.PI/2;floor.position.y=-.045;floor.receiveShadow=true;scene.add(floor);scene.add(new T.HemisphereLight('#fff5df','#524738',1.5));const key=new T.DirectionalLight('#fff4df',3);key.position.set(-4,8,5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.radius=4;key.shadow.blurSamples=8;key.shadow.camera.near=.5;key.shadow.camera.far=22;Object.assign(key.shadow.camera,{left:-6,right:6,top:6,bottom:-6});key.shadow.normalBias=.003;key.shadow.bias=-.0002;scene.add(key);
 let disposed=false,frame=0;let current={...initial.current};let target={...current};const render=()=>{if(!disposed)renderer.render(scene,camera)};
 function apply(v:Props){const p=v.progress,open=clamp(v.reveal),lift=clamp(v.reveal-1);walls.forEach(w=>w.rotation.x=-clamp(p/.5)*Math.PI/2);roofs.forEach((r,i)=>{r.rotation.x=(-1.142*clamp((p-.5)/.5))*(1-open)+open*1.15;tabs[i].rotation.x=-.429*clamp((p-.75)/.25)*(1-open);tails[i].rotation.x=-Math.PI/2*clamp((p-.92)/.08)*(1-open);seams[i].rotation.z=clamp(p/.5)*Math.PI/3});tray.position.set(0,.62+(1-clamp((p-.42)/.33))*1.4+lift*.35,0);tray.visible=p>.4;crown.position.set(0,1.33+(1-clamp((p-.65)/.35))*.8+open*.55+lift*.18,0);crown.visible=p>.65;
  const palettes=[['#c8bda6','#978a73','#aea18b'],['#242421','#4c4942','#33322d'],['#c2c0b9','#797b78','#999e9a']];stock.color.set(palettes[v.material][0]);edge.color.set(palettes[v.material][1]);inner.color.set(palettes[v.material][2]);stock.roughness=[.87,.78,.46][v.material];stock.bumpScale=[.018,.009,.002][v.material];emboss.visible=v.finish===1;registered.visible=v.finish===2;annotations.visible=p<.22;annotations.scale.y=1;ink.opacity=.55;camera.position.set(6-p*2.5,8-p*4,8-p*2.5);camera.lookAt(0,.35+p*.20,0);render();}
 const tick=()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const delta=Math.abs(current.reveal-target.reveal);current={...target,reveal:reduced?target.reveal:current.reveal+(target.reveal-current.reveal)*.13};apply(current);if(delta>.002&&!reduced)frame=requestAnimationFrame(tick);else{current={...target};apply(current);frame=0}};
 update.current=v=>{target=v;if(!frame)tick()};const resize=()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight);apply(current)};const ro=new ResizeObserver(resize);ro.observe(el);resize();const loss=(e:Event)=>{e.preventDefault();setFailed(true)};renderer.domElement.addEventListener('webglcontextlost',loss);
 return()=>{disposed=true;cancelAnimationFrame(frame);ro.disconnect();renderer.domElement.removeEventListener('webglcontextlost',loss);geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());texture.dispose();env.dispose();renderer.dispose();renderer.domElement.remove()};
 },[]);useEffect(()=>update.current(props),[props]);return <div className="package-render" ref={host} role="img" aria-label="Six-panel radial blank assembles into a faceted shell with scored hinges, roof tongues, a slotted crown and fitted presentation tray">{failed&&<p>Interactive assembly requires WebGL. Six scored wall panels fold around a fitted tray; roof tongues engage a slotted crown.</p>}</div>
}


