import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
const ramp=(p:number,a:number,b:number)=>Math.max(0,Math.min(1,(p-a)/(b-a)));
export default function SpaceScene({progress}:{progress:number}){const host=useRef<HTMLDivElement>(null),update=useRef<(p:number)=>void>(()=>{});const[failed,setFailed]=useState(false);useEffect(()=>{const el=host.current!;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:true})}catch{setFailed(true);return}renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;el.appendChild(renderer.domElement);const scene=new T.Scene(),camera=new T.OrthographicCamera(-9,9,7,-7,.1,100);const pm=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pm.fromScene(room,.04);room.dispose();pm.dispose();scene.environment=env.texture;scene.environmentIntensity=.3;
 const plaster=new T.MeshStandardMaterial({color:'#b9b7ad',roughness:.9}),timber=new T.MeshStandardMaterial({color:'#56483a',roughness:.84}),metal=new T.MeshStandardMaterial({color:'#454a47',roughness:.48,metalness:.35}),seat=new T.MeshStandardMaterial({color:'#aba28e',roughness:.9}),peopleMat=new T.MeshStandardMaterial({color:'#71513f',roughness:1}),massMat=new T.MeshStandardMaterial({color:'#c9c9c2',roughness:1,transparent:true,opacity:.4}),lineMat=new T.LineBasicMaterial({color:'#5f6d68',transparent:true,opacity:.6}),pathMat=new T.LineBasicMaterial({color:'#a05a43',transparent:true,opacity:.9});const mats:T.Material[]=[plaster,timber,metal,seat,peopleMat,massMat,lineMat,pathMat],geos:T.BufferGeometry[]=[];const structural=new T.Group(),material=new T.Group(),human=new T.Group(),occupation=new T.Group(),mass=new T.Group(),base=new T.Group();scene.add(structural,material,human,occupation,mass,base);
 function box(w:number,h:number,d:number,x:number,y:number,z:number,mat:T.Material,parent:T.Object3D){const g=new T.BoxGeometry(w,h,d);geos.push(g);const m=new T.Mesh(g,mat);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;parent.add(m);return m}
 function trace(points:number[][],mat:T.LineBasicMaterial=lineMat){const g=new T.BufferGeometry().setFromPoints(points.map(([x,y,z])=>new T.Vector3(x,y,z)));geos.push(g);const l=new T.Line(g,mat);scene.add(l);return l}
 // Three modular wings hold the edges of one open court.
 const wings=[[-4,0,2.5,6],[4,0,2.5,6],[0,-3.7,5.5,2.4]];
 for(const[x,z,w,d]of wings){box(w,.16,d,x,.03,z,plaster,base);box(w,2.7,d,x,1.4,z,massMat,mass);trace([[x-w/2,.14,z-d/2],[x+w/2,.14,z-d/2],[x+w/2,.14,z+d/2],[x-w/2,.14,z+d/2],[x-w/2,.14,z-d/2]]);for(const sx of [-1,1])for(const sz of [-1,1]){box(.12,2.75,.12,x+sx*(w/2-.18),1.48,z+sz*(d/2-.18),metal,structural)}for(const sx of [-1,1])box(.13,.20,d,x+sx*(w/2-.18),2.9,z,timber,structural);for(let j=0;j<Math.floor(d/.3);j++)box(w,.12,.095,x,3.04,z-d/2+.15+j*.3,timber,structural)}
 const courtGeo=new T.CylinderGeometry(2.35,2.35,.08,80);geos.push(courtGeo);const court=new T.Mesh(courtGeo,plaster);court.position.y=.03;court.receiveShadow=true;base.add(court);const outline=[];for(let i=0;i<=80;i++)outline.push([Math.cos(i/80*Math.PI*2)*2.35,.1,Math.sin(i/80*Math.PI*2)*2.35]);trace(outline);box(1.5,.05,3.9,0,0,4.1,plaster,base);
 // Retreat timber screen, conversation bench, and a low presentation platform.
 for(let i=0;i<24;i++)box(.09,2.45,.065,-5.20,1.30,-2.7+i*.235,timber,material);box(2,.45,.65,-4,.37,-1.8,seat,material);box(2,.45,.65,-4,.37,1.8,seat,material);box(.65,.45,4.5,4.75,.37,0,seat,material);box(3.5,.30,1.5,0,.31,-3.7,timber,material);box(3,.03,.8,0,1.07,-3.7,seat,material);for(const x of [-1.2,1.2])box(.06,.7,.6,x,.72,-3.7,metal,material);
 const path=trace([[0,.18,6],[0,.18,2.7],[0,.18,.2],[-2.5,.18,.2],[-4,.18,.2],[-2.5,.18,.2],[0,.18,.2],[2.5,.18,.2],[4,.18,.2],[2.5,.18,.2],[0,.18,.2],[0,.18,-3.7]],pathMat);
 function person(x:number,z:number,angle:number,parent:T.Object3D){const g=new T.Group();g.position.set(x,.12,z);g.rotation.y=angle;parent.add(g);const bodyG=new T.CapsuleGeometry(.14,.58,4,12);geos.push(bodyG);const body=new T.Mesh(bodyG,peopleMat);body.position.y=1.08;body.castShadow=true;g.add(body);const headG=new T.SphereGeometry(.12,16,12);geos.push(headG);const head=new T.Mesh(headG,peopleMat);head.position.y=1.58;head.castShadow=true;g.add(head);for(const offset of [-.1,.1])box(.09,.64,.11,offset,.35,0,peopleMat,g);for(const offset of [-.22,.22]){const arm=box(.075,.56,.08,offset,.99,0,peopleMat,g);arm.rotation.z=offset>0?-.1:.1}return g}
 person(0,3.5,0,human);for(const[x,z,a]of [[-.7,.5,.6],[.7,.4,-.6],[0,-.6,2.8],[3.8,1,1.3],[3.8,-.4,-1.3],[-3.8,1.1,.5],[.5,-3,0]])person(x,z,a,occupation);
 const ambient=new T.HemisphereLight('#fffbed','#697772',2);scene.add(ambient);const sun=new T.DirectionalLight('#fff0d4',2.3);sun.position.set(-6,10,6);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-10,right:10,top:10,bottom:-10});sun.shadow.normalBias=.025;scene.add(sun);const floorG=new T.PlaneGeometry(100,100);geos.push(floorG);const shadow=new T.ShadowMaterial({opacity:.18});mats.push(shadow);const floor=new T.Mesh(floorG,shadow);floor.rotation.x=-Math.PI/2;floor.position.y=-.06;floor.receiveShadow=true;scene.add(floor);let disposed=false,last=0;
 update.current=p=>{last=p;const rise=ramp(p,0,.16),structure=ramp(p,.17,.29),mat=ramp(p,.43,.58),light=ramp(p,.58,.72);mass.visible=p>.01&&p<.32;mass.scale.y=Math.max(.01,rise);massMat.opacity=.48*(1-structure);structural.scale.y=Math.max(.001,structure);structural.visible=p>.16;material.visible=p>.40;material.scale.y=Math.max(.01,mat);timber.color.set(mat>.5?'#56483a':'#a3a69e');plaster.color.set(mat>.5?'#b9b7ad':'#d1d2cb');human.visible=p>.72;human.scale.y=ramp(p,.72,.84);occupation.visible=p>.85;occupation.scale.y=ramp(p,.85,1);path.visible=p>.30&&p<.85;path.geometry.setDrawRange(0,Math.floor(ramp(p,.30,.43)*12));sun.intensity=1.8+light*.8;sun.position.set(-6+light*9,10-light*3,6);ambient.intensity=2-light*.7;const tilt=ramp(p,0,.32);camera.position.set(12*tilt,20-tilt*7,.02+17*tilt);camera.lookAt(0,.7,0);if(!disposed)renderer.render(scene,camera)};
 const resize=()=>{const aspect=el.clientWidth/el.clientHeight;const extent=aspect<1?8.5:7.4;camera.left=-extent*aspect;camera.right=extent*aspect;camera.top=extent;camera.bottom=-extent;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight);update.current(last)};const ro=new ResizeObserver(resize);ro.observe(el);resize();const loss=(e:Event)=>{e.preventDefault();setFailed(true)};renderer.domElement.addEventListener('webglcontextlost',loss);return()=>{disposed=true;ro.disconnect();renderer.domElement.removeEventListener('webglcontextlost',loss);geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());env.dispose();renderer.dispose();renderer.domElement.remove()};},[]);useEffect(()=>update.current(progress),[progress]);return <div className="space-render" ref={host} role="img" aria-label="One modular social pavilion: an open circular gathering court between a western screened retreat, eastern conversation bench and northern presentation platform. An arrival path connects all three wings.">{failed&&<p>WebGL unavailable. The pavilion has an open court, three sheltered edges and one shared arrival path.</p>}</div>}
