import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {RoundedBoxGeometry} from 'three/examples/jsm/geometries/RoundedBoxGeometry.js';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
const ramp=(p:number,a:number,b:number)=>Math.max(0,Math.min(1,(p-a)/(b-a)));
export default function SpaceScene({progress}:{progress:number}){const host=useRef<HTMLDivElement>(null),update=useRef<(p:number)=>void>(()=>{});const[failed,setFailed]=useState(false);useEffect(()=>{const el=host.current!;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:true})}catch{setFailed(true);return}renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;el.appendChild(renderer.domElement);const scene=new T.Scene(),camera=new T.OrthographicCamera(-9,9,7,-7,.1,100);const pm=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pm.fromScene(room,.04);room.dispose();pm.dispose();scene.environment=env.texture;scene.environmentIntensity=.3;
 const textures:T.Texture[]=[];
 function grain(direction:boolean){const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d')!;ctx.fillStyle='#999999';ctx.fillRect(0,0,256,256);let seed=51;for(let i=0;i<5000;i++){seed=(seed*1664525+1013904223)>>>0;const x=seed%256;seed=(seed*1664525+1013904223)>>>0;const y=seed%256;ctx.fillStyle=`rgba(${i%2?30:240},${i%2?30:240},${i%2?30:240},.12)`;ctx.fillRect(x,y,direction?25+seed%55:1,direction?.5:1)}const t=new T.CanvasTexture(c);t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(direction?2:5,direction?3:5);textures.push(t);return t}
 const timberGrain=grain(true),mineralGrain=grain(false);
 const plaster=new T.MeshStandardMaterial({color:'#b9b7ad',roughness:.94,bumpMap:mineralGrain,bumpScale:.017}),timber=new T.MeshStandardMaterial({color:'#56483a',roughness:.78,bumpMap:timberGrain,bumpScale:.011}),metal=new T.MeshStandardMaterial({color:'#454a47',roughness:.32,metalness:.65}),seat=new T.MeshStandardMaterial({color:'#aba28e',roughness:.9}),peopleMat=new T.MeshStandardMaterial({color:'#515650',roughness:1}),massMat=new T.MeshStandardMaterial({color:'#c9c9c2',roughness:1,transparent:true,opacity:.4}),lineMat=new T.LineBasicMaterial({color:'#5f6d68',transparent:true,opacity:.6}),pathMat=new T.LineBasicMaterial({color:'#a05a43',transparent:true,opacity:.9});const mats:T.Material[]=[plaster,timber,metal,seat,peopleMat,massMat,lineMat,pathMat],geos:T.BufferGeometry[]=[];const structural=new T.Group(),material=new T.Group(),human=new T.Group(),occupation=new T.Group(),mass=new T.Group(),base=new T.Group();scene.add(structural,material,human,occupation,mass,base);
 function box(w:number,h:number,d:number,x:number,y:number,z:number,mat:T.Material,parent:T.Object3D){const g=new RoundedBoxGeometry(w,h,d,2,Math.min(.012,w*.12,h*.12,d*.12));geos.push(g);const m=new T.Mesh(g,mat);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;parent.add(m);return m}
 function trace(points:number[][],mat:T.LineBasicMaterial=lineMat){const g=new T.BufferGeometry().setFromPoints(points.map(([x,y,z])=>new T.Vector3(x,y,z)));geos.push(g);const l=new T.Line(g,mat);scene.add(l);return l}
 // Three modular wings hold the edges of one open court.
 const timberTones=Array.from({length:7},(_,i)=>{const m=timber.clone();m.color.set(['#584b3a','#695844','#62513e','#725e49','#514332','#675541','#5d503f'][i]);mats.push(m);return m});let boardIndex=0;
 const wings=[[-4,0,2.5,6],[4,0,2.5,6],[0,-3.7,5.5,2.4]];
 for(const[x,z,w,d]of wings){box(w,.16,d,x,.03,z,plaster,base);box(w,2.7,d,x,1.4,z,massMat,mass);trace([[x-w/2,.14,z-d/2],[x+w/2,.14,z-d/2],[x+w/2,.14,z+d/2],[x-w/2,.14,z+d/2],[x-w/2,.14,z-d/2]]);for(const sx of [-1,1])for(const sz of [-1,1]){box(.12,2.75,.12,x+sx*(w/2-.18),1.48,z+sz*(d/2-.18),metal,structural);box(.21,.045,.21,x+sx*(w/2-.18),.14,z+sz*(d/2-.18),metal,structural);box(.18,.045,.22,x+sx*(w/2-.18),2.79,z+sz*(d/2-.18),metal,structural)}for(const sx of [-1,1])box(.13,.20,d,x+sx*(w/2-.18),2.9,z,timber,structural);for(let j=0;j<Math.floor(d/.3);j++)box(w,.12,.095,x,3.04,z-d/2+.15+j*.3,timberTones[boardIndex++%7],structural)}
 const courtGeo=new T.CylinderGeometry(2.35,2.35,.08,80);geos.push(courtGeo);const court=new T.Mesh(courtGeo,plaster);court.position.y=.03;court.receiveShadow=true;base.add(court);const outline=[];for(let i=0;i<=80;i++)outline.push([Math.cos(i/80*Math.PI*2)*2.35,.1,Math.sin(i/80*Math.PI*2)*2.35]);trace(outline);box(1.5,.05,3.9,0,0,4.1,plaster,base);
 // Retreat timber screen, conversation bench, and a low presentation platform.
 for(let i=0;i<24;i++)box(.09,2.45,.065,-5.20,1.30,-2.7+i*.235,timber,material);box(2,.45,.65,-4,.37,-1.8,seat,material);box(2,.45,.65,-4,.37,1.8,seat,material);box(.65,.45,4.5,4.75,.37,0,seat,material);box(3.5,.30,1.5,0,.31,-3.7,timber,material);box(3,.03,.8,0,1.07,-3.7,seat,material);for(const x of [-1.2,1.2])box(.06,.7,.6,x,.72,-3.7,metal,material);
 const path=trace([[0,.18,6],[0,.18,2.7],[0,.18,.2],[-2.5,.18,.2],[-4,.18,.2],[-2.5,.18,.2],[0,.18,.2],[2.5,.18,.2],[4,.18,.2],[2.5,.18,.2],[0,.18,.2],[0,.18,-3.7]],pathMat);
 const humanInk=peopleMat.clone(),occupationInk=peopleMat.clone();humanInk.transparent=occupationInk.transparent=true;mats.push(humanInk,occupationInk);
 // Architectural cut-out figures: different poses articulate arrival, seating and exchange.
 function person(x:number,z:number,angle:number,parent:T.Object3D,pose:'walk'|'stand'|'seat'|'present'='stand'){
 const figureInk=parent===human?humanInk:occupationInk;const g=new T.Group();g.position.set(x,.12,z);g.rotation.y=angle;parent.add(g);
 const seated=pose==='seat';const torso=new T.Shape();const pts=seated?[[-.13,.58],[-.15,1.02],[-.07,1.13],[.07,1.13],[.16,1.01],[.15,.65],[.34,.61],[.35,.49],[-.1,.49]]:[[-.14,.80],[-.15,1.11],[-.2,1.35],[-.07,1.46],[.07,1.46],[.2,1.35],[.15,1.11],[.14,.8]];
 pts.forEach(([x,y],i)=>i?torso.lineTo(x,y):torso.moveTo(x,y));torso.closePath();const geo=new T.ExtrudeGeometry(torso,{depth:.055,bevelEnabled:true,bevelSize:.018,bevelThickness:.012,bevelSegments:2,steps:1});geos.push(geo);const body=new T.Mesh(geo,figureInk);body.castShadow=true;g.add(body);
 const hg=new T.SphereGeometry(.10,16,12);geos.push(hg);const head=new T.Mesh(hg,figureInk);head.scale.set(.82,1.15,.58);head.position.set(0,seated?1.27:1.60,.02);head.castShadow=true;g.add(head);
 function limb(points:number[][],radius=.045){const curve=new T.CatmullRomCurve3(points.map(([a,b,c])=>new T.Vector3(a,b,c)));const geo=new T.TubeGeometry(curve,8,radius,6,false);geos.push(geo);const mesh=new T.Mesh(geo,figureInk);mesh.castShadow=true;g.add(mesh)}
 if(seated){limb([[-.06,.57,.02],[.29,.55,.02],[.30,.12,.02]]);limb([[.04,.57,.04],[.36,.53,.04],[.4,.12,.04]]);limb([[-.13,1.02,.02],[-.2,.78,.02],[.16,.70,.02]],.034);limb([[.13,1.02,.02],[.23,.84,.02],[.20,.7,.02]],.034)}else{const stride=pose==='walk'?.20:.06;limb([[-.08,.88,.02],[-.10-stride,.43,.02],[-.1-stride,.06,.02]]);limb([[.08,.88,.02],[.12+stride,.45,.02],[.13+stride,.06,.02]]);limb([[-.17,1.33,.02],[-.24,1.10,.02],[-.19,.93,.02]],.033);limb(pose==='present'?[[.17,1.33,.02],[.37,1.19,.02],[.61,1.30,.02]]:[[.17,1.33,.02],[.25,1.10,.02],[.34,1.12,.02]],.033)}return g}
 person(0,3.5,.25,human,'walk');
 person(-.8,.45,.5,occupation);person(.55,.65,-.35,occupation);person(.15,-.75,2.8,occupation);
 person(3.65,.5,-.55,occupation);person(3.7,-.8,2.7,occupation);
 person(-3.8,1.78,.4,occupation,'seat');person(.2,-3.65,.3,occupation,'present');
 // Site and glazing are representational layers; the approved footprint and structure stay fixed.
 const site=new T.Group();scene.add(site);const ground=new T.MeshStandardMaterial({color:'#d1cbbc',roughness:1,bumpMap:mineralGrain,bumpScale:.022});mats.push(ground);box(12.3,.10,12.5,0,-.14,.4,ground,site);
 for(const z of [-5.5,-4.5,5.5,6.5]){const l=trace([[-6.1,-.078,z],[6.1,-.078,z]]);site.add(l)}
 const glass=new T.MeshPhysicalMaterial({color:'#c1d4ce',roughness:.15,metalness:0,transparent:true,opacity:.24,depthWrite:false,side:T.DoubleSide});mats.push(glass);
 for(const z of [-1.45,.05]){const pane=box(.024,1.7,1.5,-5.08,1.01,z,glass,material);pane.castShadow=false;box(.03,.025,1.5,-5.07,1.87,z,metal,material)}
 const notation=new T.Group();scene.add(notation);
 function label(text:string,x:number,y:number,z:number,width:number){const c=document.createElement('canvas');const measure=c.getContext('2d')!;measure.font='32px monospace';c.width=Math.ceil(measure.measureText(text).width)+16;c.height=52;const ctx=c.getContext('2d')!;ctx.fillStyle='#40483f';ctx.font='32px monospace';ctx.fillText(text,8,37);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;textures.push(t);const m=new T.SpriteMaterial({map:t,transparent:true,depthTest:false});mats.push(m);const sprite=new T.Sprite(m);sprite.position.set(x,y,z);sprite.scale.set(width,width*52/c.width,1);notation.add(sprite);return sprite}
 const section=trace([[-5.8,.20,-3.7],[5.8,.20,-3.7]],pathMat);const sectionLabel=label('A-A / STRUCTURE',-5.7,.3,-4.1,2.4);
 const materialLabel=label('TIMBER / MINERAL / METAL',-3.5,3.7,-2.8,4);
 const sunlight=trace([[6,5.5,-5],[1,2.8,0]],pathMat);const sunLabel=label('FILTERED / AFTERNOON',4.8,5.2,-4.5,3.2);
 const dimension=trace([[1.1,.12,3.5],[1.1,1.82,3.5],[.95,1.82,3.5],[1.25,1.82,3.5]],pathMat);const dimensionLabel=label('1.70 m',1.9,1.4,3.5,1.3);
 const occupationLabels=[label('ARRIVE',0,.3,5.8,1.4),label('GATHER',0,.3,1.7,1.4),label('CONVERSE',5.8,.7,.4,1.8),label('RETREAT',-5.8,.7,2.7,1.7),label('PRESENT',.3,2,-3.7,1.7)];
 const ambient=new T.HemisphereLight('#fffbed','#697772',2);scene.add(ambient);const sun=new T.DirectionalLight('#fff0d4',2.3);sun.position.set(-6,10,6);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-10,right:10,top:10,bottom:-10});sun.shadow.normalBias=.025;scene.add(sun);const floorG=new T.PlaneGeometry(100,100);geos.push(floorG);const shadow=new T.ShadowMaterial({opacity:.18});mats.push(shadow);const floor=new T.Mesh(floorG,shadow);floor.rotation.x=-Math.PI/2;floor.position.y=-.06;floor.receiveShadow=true;scene.add(floor);let disposed=false,last=0;
 update.current=p=>{last=p;const rise=ramp(p,0,.16),structure=ramp(p,.17,.29),mat=ramp(p,.43,.58),light=ramp(p,.58,.72);mass.visible=p>.01&&p<.32;mass.scale.y=Math.max(.01,rise);massMat.opacity=.48*(1-structure);structural.scale.y=Math.max(.001,structure);structural.visible=p>.16;material.visible=p>.40;material.scale.y=Math.max(.01,mat);timber.color.copy(new T.Color('#a3a69e').lerp(new T.Color('#56483a'),mat));timberTones.forEach((m,i)=>m.color.copy(new T.Color('#a3a69e').lerp(new T.Color(['#584b3a','#695844','#62513e','#725e49','#514332','#675541','#5d503f'][i]),mat)));plaster.color.copy(new T.Color('#d1d2cb').lerp(new T.Color('#b9b7ad'),mat));site.visible=p>.43;ground.color.copy(new T.Color('#e0ded4').lerp(new T.Color('#c9c3b3'),mat));section.visible=sectionLabel.visible=p>.17&&p<.34;materialLabel.visible=p>.48&&p<.64;sunlight.visible=sunLabel.visible=p>=.64&&p<.77;dimension.visible=dimensionLabel.visible=p>=.77&&p<.92;occupationLabels.forEach(l=>l.visible=p>.96);human.visible=p>.72;humanInk.opacity=ramp(p,.72,.84);occupation.visible=p>.88;occupationInk.opacity=ramp(p,.88,1);path.visible=p>.30&&p<.50;path.geometry.setDrawRange(0,Math.floor(ramp(p,.30,.43)*12));sun.intensity=1.8+light*1.35;sun.position.set(-6+light*11,10-light*5,6-light*10);ambient.intensity=2-light*1.05;const tilt=ramp(p,0,.32);camera.position.set(12*tilt,20-tilt*7,.02+17*tilt);camera.lookAt(0,.7,0);if(!disposed)renderer.render(scene,camera)};
 const resize=()=>{const aspect=el.clientWidth/el.clientHeight;const extent=aspect<1?8.5:7.4;camera.left=-extent*aspect;camera.right=extent*aspect;camera.top=extent;camera.bottom=-extent;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight);update.current(last)};const ro=new ResizeObserver(resize);ro.observe(el);resize();const loss=(e:Event)=>{e.preventDefault();setFailed(true)};renderer.domElement.addEventListener('webglcontextlost',loss);return()=>{disposed=true;ro.disconnect();renderer.domElement.removeEventListener('webglcontextlost',loss);textures.forEach(t=>t.dispose());geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());env.dispose();renderer.dispose();renderer.domElement.remove()};},[]);useEffect(()=>update.current(progress),[progress]);return <div className="space-render" ref={host} role="img" aria-label="One modular social pavilion: an open circular gathering court between a western screened retreat, eastern conversation bench and northern presentation platform. An arrival path connects all three wings.">{failed&&<p>WebGL unavailable. The pavilion has an open court, three sheltered edges and one shared arrival path.</p>}</div>}


