import {useState,type CSSProperties} from 'react';
import {createRoot} from 'react-dom/client';
import {installMotionTokens} from '../experience/tokens';
import {studies,relationships,intents,studyHref} from './data';
import './proof.css';
installMotionTokens();
const base='/capability-gateway-proof';
const number=(i:number)=>String(i+1).padStart(2,'0');
function Header({concept}:{concept:string}){return <header className="gateway-header"><a href={base} className="signature">DYNASTY WORKS<span>STUDIO</span></a><span className="proof-context">CAPABILITY GATEWAY <i>/</i> {concept}</span><a href={base} className="compare">Compare A / C <span aria-hidden="true">↗</span></a></header>}
function Disclosure(){return <p className="disclosure">Original DWS capability demonstrations.<br/>Independent studies. No client engagement.</p>}
function Genesis({strong=false}:{strong?:boolean}){return <section className={'genesis-threshold '+(strong?'is-emphasized':'')} aria-labelledby="capstone"><div><span className="micro">THE CAPSTONE / GENESIS</span><h2 id="capstone">See an idea<br/><em>become a company.</em></h2></div><div className="threshold-end"><p>Not another discipline.<br/>The consequence of working together.</p><a href="/genesis-full/">Enter Genesis <span aria-hidden="true">↗</span></a><small>Interactive company simulation · illustrative data</small></div></section>}
function Index(){return <details className="all-studies"><summary>All nine disciplines <span aria-hidden="true">＋</span></summary><nav aria-label="All capability studies">{studies.map((s,i)=><a key={s.slug} href={studyHref(i)}><span>{number(i)}</span><strong>{s.name}</strong><small>{s.discipline}</small><span aria-hidden="true">↗</span></a>)}</nav></details>}
const positions=[[5,12],[37,6],[65,17],[7,46],[39,42],[64,51],[3,80],[37,78],[76,84]];
function Score(){const[active,setActive]=useState<number|null>(null);const related=active===null?[]:relationships[active];const s=active===null?null:studies[active];return <div className="gateway score"><Header concept="A / THE DISCIPLINE SCORE"/><main id="main"><div className="score-intro"><h1>Intelligence<br/><em>in relation.</em></h1><div><span className="micro">NINE DISCIPLINES / ONE PRACTICE</span><p>Nothing is built<br/>in isolation.</p><Disclosure/></div></div><section className={'score-field '+(active!==null?'has-selection':'')} aria-label="Relational discipline score"><svg viewBox="0 0 1000 370" preserveAspectRatio="none" aria-hidden="true">{related.map(r=><path key={r.id} d={`M${positions[active!][0]*10+70},${positions[active!][1]*3.7+12} H${positions[r.id][0]*10+70} V${positions[r.id][1]*3.7+12}`}/>)}</svg>{studies.map((item,i)=>{const selected=active===i,isRelated=related.some(r=>r.id===i);return <button key={item.slug} className={'score-word '+(selected?'selected':isRelated?'related':'')} style={{'--x':positions[i][0]+'%','--y':positions[i][1]+'%'} as CSSProperties} aria-pressed={selected} aria-controls="score-detail" onFocus={()=>setActive(i)} onClick={()=>setActive(i)}><span className="score-number">{number(i)}</span><span>{item.short}</span><small>{selected?item.name:isRelated?'IN RELATION':''}</small></button>})}</section><section id="score-detail" className="score-detail" aria-live="polite"><span className="detail-index">{active===null?'—':number(active)}</span><div className="selected-study"><span className="micro">{s?'CAPABILITY STUDY':'SELECT A DISCIPLINE'}</span><h2>{s?s.name:'One decision touches another.'}</h2><p>{s?s.copy:'Select an intelligence to see what it makes possible, and which disciplines it works alongside.'}</p>{s&&<a className="entry" href={studyHref(active!)}>Enter study <span aria-hidden="true">↗</span></a>}</div><div className="relationship-notes">{active===null?<p className="quiet-note">A relationship is not a dependency.<br/>Enter anywhere.</p>:<><span className="micro">WORKS ALONGSIDE</span>{related.map(r=><button key={r.id} onClick={()=>setActive(r.id)}><strong>{studies[r.id].short} <span aria-hidden="true">↗</span></strong><span>{r.why}</span></button>)}</>}</div></section><Index/><Genesis strong={active!==null}/></main><Footer/></div>}
function Lens(){const[intent,setIntent]=useState<number|null>(null),[artifact,setArtifact]=useState<number|null>(null),[cursor,setCursor]=useState(0);const pick=(i:number)=>{setIntent(i);setArtifact(null)};return <div className="gateway lens"><Header concept="C / THE COMMISSION LENS"/><main id="main"><section className="lens-opening"><span className="micro">BEGIN WITH THE COMMISSION</span><h1>What are<br/><em>we building?</em></h1><div className="lens-subline"><p>A practical starting point.<br/>More than one kind of intelligence.</p><Disclosure/></div><div className="mobile-intent" aria-label="Explore commissioning intents"><span className="micro">CHOOSE A STARTING POINT / {number(cursor)} OF 09</span><div><button aria-label="Previous intent" onClick={()=>setCursor((cursor+8)%9)}>←</button><button className="current-intent" aria-pressed={intent===cursor} onClick={()=>pick(cursor)}>{intents[cursor].name}<small>Explore this mix ↗</small></button><button aria-label="Next intent" onClick={()=>setCursor((cursor+1)%9)}>→</button></div></div><div className="intent-list" role="group" aria-label="Commissioning intent">{intents.map((item,i)=><button key={item.name} aria-pressed={intent===i} aria-controls="intelligence-mix" onClick={()=>pick(i)}><span>{item.name}</span><b aria-hidden="true">{intent===i?'↗':'+'}</b></button>)}</div></section><section id="intelligence-mix" className={'mix '+(intent!==null?'is-resolved':'')} aria-live="polite"><div className="mix-heading"><span className="micro">{intent===null?'YOUR INTELLIGENCE MIX':'A POSSIBLE INTELLIGENCE MIX'}</span><h2>{intent===null?<>The intention<br/><em>sets the direction.</em></>:intents[intent].line}</h2><p>Orientation, not a scored recommendation.<br/>Each study demonstrates a discipline, not a client project.</p></div>{intent!==null&&<><div className="mix-words" aria-label="Relevant capability studies">{intents[intent].mix.map(i=><button key={i} aria-pressed={artifact===i} aria-controls="lens-artifact" onClick={()=>setArtifact(i)}><sup>{number(i)}</sup>{studies[i].short}<span aria-hidden="true">↗</span></button>)}</div><div className="artifact-entry" id="lens-artifact">{artifact===null?<p>Select an intelligence to examine its capability study.</p>:<><span className="micro">CAPABILITY STUDY / {number(artifact)}</span><h3>{studies[artifact].name}</h3><p>{studies[artifact].copy}</p><a className="entry" href={studyHref(artifact)}>Enter study <span aria-hidden="true">↗</span></a></>}</div></>}</section><Genesis strong={intent===8}/><Index/></main><Footer/></div>}
function Footer(){return <footer className="gateway-footer"><span>DWS / ORIGINAL DEMONSTRATIONS</span><span>Private discovery proof · A / C</span><a href={base}>Comparison ↗</a></footer>}
function Comparison(){return <div className="gateway comparison"><Header concept="FOUNDER COMPARISON"/><main id="main"><span className="micro">TWO ENTRANCES / THE SAME NINE DISCIPLINES</span><h1>How do you<br/><em>want to discover?</em></h1><p>Two discovery architectures. No preferred direction.</p><nav aria-label="Compare gateway concepts"><a href={base+'/a'}><span>A</span><div><h2>The Discipline Score</h2><p>Begin with relationships.<br/>Relational / exploratory / systemic</p></div><b aria-hidden="true">↗</b></a><a href={base+'/c'}><span>C</span><div><h2>The Commission Lens</h2><p>Begin with intent.<br/>Orienting / practical / commercial</p></div><b aria-hidden="true">↗</b></a></nav><Disclosure/></main><Footer/></div>}
const path=location.pathname.replace(/\/$/,'');document.title=path.endsWith('/a')?'The Discipline Score — DWS':path.endsWith('/c')?'The Commission Lens — DWS':'Capability Gateway A/C — DWS';createRoot(document.getElementById('root')!).render(<><a className="skip" href="#main">Skip to experience</a>{path.endsWith('/a')?<Score/>:path.endsWith('/c')?<Lens/>:<Comparison/>}</>);

