import {useEffect,useState} from 'react';
import {MaterialImage} from './LivingSystem';
import type {LivingAsset} from './living-assets';

export function CreationSignal({reduced=false}:{reduced?:boolean}){
 const[phase,setPhase]=useState(0);const[manual,setManual]=useState(false);
 useEffect(()=>{if(reduced||manual)return;const preference=window.matchMedia('(prefers-reduced-motion: reduce)');if(preference.matches)return;const first=window.setTimeout(()=>setPhase(1),900);const second=window.setTimeout(()=>setPhase(2),1800);const stop=()=>{clearTimeout(first);clearTimeout(second)};preference.addEventListener('change',stop);return()=>{stop();preference.removeEventListener('change',stop)}},[reduced,manual]);
 function advance(){setManual(true);setPhase(current=>(current+1)%3)}
 return <div className={'creation-signal signal-'+phase}><div className="signal-drawing" aria-hidden="true"><i className="signal-origin"/><div className="signal-spine"/>{['Strategy','Identity','Product','Technology','Market'].map((name,i)=><div className="signal-member" key={name} style={{'--member':i} as React.CSSProperties}><span>{name}</span></div>)}</div><div className="signal-caption"><span aria-live="polite">{['01 / Idea','02 / Relationship','03 / Company system'][phase]}</span><button onClick={advance} aria-label={phase===2?'Restart creation signal':'Advance creation signal'}>{phase===2?'Begin again':'Build on it'} →</button></div></div>
}

export function CompanyArchitecture({operations=false}:{operations?:boolean}){return <div className={'company-architecture '+(operations?'is-operations':'')} role="img" aria-label={operations?'Information moves through review and approved action, with a feedback loop.':'Purpose connects people, position and proposition to a company roadmap.'}><div className="architecture-root">{operations?'Information':'Purpose'}</div><div className="architecture-branches">{(operations?['Review','Approval','Action']:['People','Position','Proposition']).map((s,i)=><div key={s}><small>0{i+1}</small><span>{s}</span></div>)}</div><div className="architecture-result">{operations?'Feedback → next decision':'One company roadmap'}</div></div>}

const stages=[['Define','Find the company inside the idea.','Research / Positioning / Roadmap'],['Build','Turn the direction into working assets.','Identity / Product / Digital'],['Launch','Connect the company to its market.','Campaign / Sales materials / Activation'],['Scale','Strengthen what works. Build what comes next.','Automation / Optimization / New markets']];
export function TransformingStage(){const[active,setActive]=useState(0);const media:(LivingAsset|null)[]=[null,'materialCraft','physicalExperience','scale'];return <section id="method" className={'transforming-stage movement-'+active}><header className="stage-intro"><p>How we build</p><h2>Four moves.<br/><em>One direction.</em></h2></header><div className="stage-canvas"><div className="stage-media">{media[active]?<MaterialImage key={media[active]} asset={media[active]} sizes="(max-width:800px) 100vw, 70vw"/>:<CompanyArchitecture/>}</div><div className="stage-selection" aria-label="Explore our methodology">{stages.map(([name],i)=><button key={name} aria-pressed={active===i} aria-controls="stage-description" onClick={()=>setActive(i)}><small>0{i+1}</small><span>{name}</span></button>)}</div><div id="stage-description" className="stage-description" aria-live="polite"><h3>{stages[active][1]}</h3><p>{stages[active][2]}</p><span>{active?'Conceptual visualization':'Company architecture'}</span></div><button className="stage-next" onClick={()=>setActive((active+1)%4)} aria-label={active===3?'Return to Define':'Continue to '+stages[active+1][0]}>{active===3?'Return to Define':'Next: '+stages[active+1][0]} <span aria-hidden="true">→</span></button></div></section>}

export function HumanMovement(){return <section className="human-movement" id="human"><h2><span>Built by</span><em>people.</em></h2><figure><MaterialImage asset="humanCreation" sizes="(max-width:800px) 100vw, 72vw"/><figcaption>Conceptual creative visualization · not a team portrait</figcaption></figure><p className="human-transfer">Amplified<br/>by systems.<span aria-hidden="true">↓</span></p></section>}
