import { useEffect, useRef, useState } from 'react';
import { startingPoints, type BusinessType, type BuildNeed } from '@/data/company-builder';
import { emptyCompanyBuild, availableNeeds, normalizeBuild } from '@/lib/company-builder';
import { generateRoadmap, roadmapText } from '@/lib/recommendation-engine';
import { businessStages, serviceById, type BusinessStage } from '@/data/service-catalog';
import type { CompanyBuild } from '@/types/company';
const suggested:BuildNeed[]=['Brand Identity','Packaging','Website','E-commerce','Application','Launch','AI / Automation','Ongoing Support','Distribution Strategy'];
export default function Diagnostic({businessType,onRestart}:{businessType:BusinessType;onRestart:()=>void}){
 const [step,setStep]=useState(0);const[stage,setStage]=useState<BusinessStage>('Idea');const[starting,setStarting]=useState<CompanyBuild['starting']>([]);const[needs,setNeeds]=useState<BuildNeed[]>([]);const[error,setError]=useState('');const[downloadPrepared,setDownloadPrepared]=useState(false);const title=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{title.current?.focus();},[step]);
 const build=normalizeBuild({...emptyCompanyBuild,businessType,businessStage:stage,starting:starting.length?starting:[startingPoints[0]],needs,uncertainNeeds:!needs.length,launch:'Exploring',budgetChoice:'Let’s define the range together'});
 const permitted=availableNeeds(build);const result=step===2?generateRoadmap(build):null;
 function next(){if(step===0&&!starting.length){setError('Select your current starting point.');return;}setError('');setStep(step+1);}
 function toggleAsset(item:CompanyBuild['starting'][number]){setStarting(current=>current.includes(item)?current.filter(x=>x!==item):item===startingPoints[0]?[item]:[...current.filter(x=>x!==startingPoints[0]),item]);}
 function download(){const url=URL.createObjectURL(new Blob([roadmapText(build)],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='dynasty-works-initial-roadmap.txt';document.body.appendChild(a);a.click();a.remove();setDownloadPrepared(true);setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="diagnostic"><div className="diagnostic-progress" aria-label={'Roadmap step '+(step+1)+' of 3'}>{[0,1,2].map(i=><span key={i} className={i<=step?'complete':''}/>)}</div><p className="step-count">{businessType} · {step+1} / 3</p><h3 ref={title} tabIndex={-1}>{['Where are you now?','What needs building?','Your first direction.'][step]}</h3>
 {step===0&&<><label htmlFor="business-stage">Business stage</label><select id="business-stage" value={stage} onChange={e=>setStage(e.target.value as BusinessStage)}>{businessStages.map(s=><option key={s}>{s}</option>)}</select><fieldset><legend>What already exists?</legend>{startingPoints.map(item=><label className="check-choice" key={item}><input type="checkbox" checked={starting.includes(item)} onChange={()=>toggleAsset(item)}/><span>{item}</span></label>)}</fieldset></>}
 {step===1&&<fieldset><legend>Select priorities, or continue to explore together.</legend>{suggested.filter(n=>permitted.includes(n)).map(item=><label className="check-choice" key={item}><input type="checkbox" checked={needs.includes(item)} onChange={()=>setNeeds(current=>current.includes(item)?current.filter(n=>n!==item):[...current,item])}/><span>{item}</span></label>)}</fieldset>}
 {error&&<p role="alert" className="form-error">{error}</p>}
 {result&&<div className="roadmap-result"><p className="result-intro">An initial recommendation based on your selections. Final scope follows a conversation.</p><ol>{result.phases.map(phase=><li key={phase.name}><h4>{phase.name}</h4><p>{phase.items.slice(0,2).map(item=>serviceById[item.serviceId].name).join(' · ')}</p></li>)}</ol><p className="result-engagement">Explore: <strong>{result.engagement.name}</strong></p><p className="instrument-note">{result.timelineNote}</p><button className="primary-action" onClick={download}>Download your roadmap <span aria-hidden="true">↓</span></button><p className="instrument-note" role="status">{downloadPrepared?"Roadmap file prepared. If the download did not start, read the full roadmap below.":"This preview does not collect contact details or submit an inquiry."}</p><details className="roadmap-text"><summary>Read the full roadmap</summary><pre>{roadmapText(build)}</pre></details></div>}
 <div className="diagnostic-actions"><button className="quiet-button" onClick={()=>step?setStep(step-1):onRestart()}>{step?'Back':'Change business type'}</button>{step<2?<button className="primary-action" onClick={next}>{step===1?'Create roadmap':'Continue'} <span aria-hidden="true">→</span></button>:<button className="quiet-button" onClick={onRestart}>Start again</button>}</div>
 </div>;
}
