import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {CompanyArchitecture} from './Creation43';
import {assetSet,dwsAssets,type LivingAsset} from './living-assets';
export function MaterialImage({asset,className='',sizes='(max-width: 800px) 100vw, 85vw'}:{asset:LivingAsset;className?:string;sizes?:string}){const data=dwsAssets[asset];return <picture className={'material-image '+className} style={{'--focus':data.focus,'--mobile-focus':data.mobileFocus} as CSSProperties}><source type="image/avif" srcSet={assetSet(asset,'avif')} sizes={sizes}/><img src={`/assets/living/${asset}-960.webp`} srcSet={assetSet(asset,'webp')} sizes={sizes} width="1536" height="1024" alt={data.alt} loading="lazy" decoding="async"/></picture>}
export function Cinema({asset,label,caption}:{asset:LivingAsset;label:string;caption:string}){const ref=useRef<HTMLElement>(null);useEffect(()=>{const el=ref.current;if(!el||!('IntersectionObserver' in window))return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){el.classList.add('has-entered');observer.disconnect();}},{threshold:.12});observer.observe(el);return()=>observer.disconnect()},[]);return <figure ref={ref} id={asset==='rawIdea'?'raw-idea':'future'} className="cinema wrap"><figcaption><span>{label}</span><p>{caption}</p></figcaption><div className="cinema-aperture"><MaterialImage asset={asset}/></div><p className="visual-caption">Conceptual visualization</p></figure>}
export function NativeStructure({operations=false}:{operations?:boolean}){return <div className={'native-structure '+(operations?'operations':'')} aria-label={operations?'Connected workflow: input, review, action.':'A direction formed from purpose, people and position.'} role="img"><svg viewBox="0 0 600 300" aria-hidden="true"><path d={operations?'M80 150H520 M200 150V70H400V150 M300 150V235':'M90 240L300 45L510 240Z M300 45V240 M90 240L405 142 M510 240L195 142'}/>{(operations?[[80,150],[200,150],[400,150],[520,150],[300,235]]:[[90,240],[300,45],[510,240]]).map(([x,y])=><circle key={x+','+y} cx={x} cy={y} r="6"/>)}</svg><p>{operations?'Input → Review → Action':'Purpose / People / Position'}</p></div>}
export function DisciplineVisual({active}:{active:number}){const[packaging,setPackaging]=useState(false);const key:LivingAsset|null=active===1?(packaging?'packaging':'brandFormation'):active===2?'productDesign':active===3?'digitalExperience':active===4?'scale':null;return <div className="discipline-world">{active===1&&<div className="sub-controls" aria-label="Brand visualization"><button aria-pressed={!packaging} onClick={()=>setPackaging(false)}>Identity</button><button aria-pressed={packaging} onClick={()=>setPackaging(true)}>Packaging</button></div>}{key?<MaterialImage key={key} asset={key} sizes="(max-width: 800px) 90vw, 80vw"/>:<CompanyArchitecture operations={active===5}/>}<div className="world-caption"><span>{key?'Conceptual visualization':'System study'}</span>{active===3&&<a href="#builder">From visualization to a working tool →</a>}</div></div>}
const steps=[['Define','Find the company inside the idea.','Research / Positioning / Roadmap'],['Build','Turn the direction into working assets.','Identity / Product / Digital'],['Launch','Connect the company to its market.','Campaign / Sales materials / Activation'],['Scale','Strengthen what works. Build what comes next.','Automation / Optimization / New markets']];
export function Method(){const[step,setStep]=useState(0);const assets:(LivingAsset|null)[]=[null,'materialCraft','physicalExperience','scale'];return <section className="method-section wrap" id="method"><div className="method-heading"><p className="kicker">HOW WE BUILD</p><h2>Four moves.<br/>One direction.</h2></div><div className="method-controls" aria-label="Explore our methodology">{steps.map(([name],i)=><button key={name} aria-pressed={step===i} aria-controls="method-stage" onClick={()=>setStep(i)}><span>0{i+1}</span>{name}</button>)}</div><div id="method-stage" className="method-stage"><div className="method-description" aria-live="polite"><h3>{steps[step][0]}</h3><p>{steps[step][1]}</p><small>{steps[step][2]}</small><p className="method-note">{['A clear direction before execution.','Detail is part of the strategy.','Beyond the screen. Brands become places, products and experiences.','Expansion begins with a connected system.'][step]}</p></div><div className="method-media">{assets[step]?<MaterialImage key={assets[step]} asset={assets[step]} sizes="(max-width: 800px) 90vw, 55vw"/>:<NativeStructure/>}<p className="visual-caption">{step?'Conceptual visualization':'From possibility to a defined direction'}</p></div></div></section>}
export function HumanBridge(){return <section className="human-bridge wrap"><figure><MaterialImage asset="humanCreation" sizes="(max-width:800px) 90vw, 45vw"/><figcaption>Conceptual creative visualization · not a team portrait</figcaption></figure><div><p className="kicker">THE HUMAN PART</p><h2>Built by people.<br/>Amplified<br/>by systems.</h2></div></section>}
export function RangeFragment({name}:{name:string}){const keys:Record<string,LivingAsset>={Brand:'brandFormation',Product:'productDesign',Digital:'digitalExperience',Content:'materialCraft',Market:'scale'};return keys[name]?<MaterialImage asset={keys[name]} sizes="(max-width:800px) 85vw, 40vw"/>:null}
