import {useState,type CSSProperties} from 'react';
import houses from './mymosa-houses.json';
import './mymosa531.css';
const products=[{name:'Classic Orange',file:'classic-orange',color:'#ef8e24'},{name:'Pineapple',file:'pineapple',color:'#e8c441'},{name:'Tropical',file:'tropical-blend',color:'#5bbbb0'},{name:'Strawberry',file:'strawberry',color:'#e75c6b'}];
const zones=[
 {id:'brand',name:'Brand zone',width:335,height:185,label:'SYSTEM CONSTANT / BRAND',copy:'The MyMosa wordmark occupies the upper label across all four expressions.'},
 {id:'classification',name:'Classification',width:335,height:110,label:'SYSTEM CONSTANT / PRODUCT',copy:'Premium Wine Cocktail sits directly below the wordmark.'},
 {id:'image',name:'Cocktail image',width:285,height:330,label:'FLAVOR VARIABLE / IMAGE',copy:'A central glass motif remains consistent; fruit cues and cocktail colors distinguish each expression.'},
 {id:'flavor',name:'Flavor name',width:345,height:155,label:'FLAVOR VARIABLE / NAMING',copy:'The flavor name occupies the same lower-middle zone across the family.'},
 {id:'information',name:'Product information',width:335,height:144,label:'SYSTEM CONSTANT / FORMAT',copy:'The lower information zone retains the 355 mL format statement.'},
];
export function BrandArchitecture(){
 const[expanded,setExpanded]=useState(false),[page,setPage]=useState(0),[selected,setSelected]=useState(1);
 const members=houses.slice(1+page*4,5+page*4);
 return <section className="m531-architecture" aria-labelledby="m531-architecture-title"><span className="m531-folio">03 / BRAND ARCHITECTURE</span><h2 id="m531-architecture-title">One product idea.<br/><em>A larger brand world.</em></h2><p className="m531-intro">The flagship became the foundation for an extensible family of premium wine cocktail concepts.</p><div className={'m531-relationship '+(expanded?'is-expanded':'')}><div className="m531-origin"><span>01 / FLAGSHIP PRODUCT &amp; BRAND</span><h3>MyMosa</h3><p>The originating product.</p></div><div className="m531-family"><span>ORGANIZING ARCHITECTURE</span><h3>My Drink<br/><em>Family</em></h3><p>A broader brand and product ecosystem.</p><button className="m531-expand" aria-expanded={expanded} aria-controls="m531-houses" onClick={()=>setExpanded(!expanded)}>{expanded?'Close the family index':'Explore the family architecture'} <span aria-hidden="true">{expanded?'−':'+'}</span></button></div></div><div id="m531-houses" hidden={!expanded}><div className="m531-index-heading"><span>BRAND-HOUSE INDEX</span><p>Concept architecture.<br/>Not a claim of commercial availability.</p></div><div className="m531-house-layout"><div className="m531-house-list" role="group" aria-label="Brand houses">{members.map(h=>{const i=houses.findIndex(x=>x.id===h.id);return <button key={h.id} aria-pressed={selected===i} onClick={()=>setSelected(i)}><small>{String(i+1).padStart(2,'0')}</small><span>{h.display}</span><i aria-hidden="true">↗</i></button>})}</div><div className="m531-house-detail" aria-live="polite"><span>MY DRINK FAMILY / HOUSE {String(selected+1).padStart(2,'0')}</span><h4>{houses[selected].display}</h4><p>{houses[selected].descriptor.toLowerCase()} reference</p><small>One named expression within the family architecture.</small></div></div><nav className="m531-pages" aria-label="House index pages">{[0,1,2,3].map(n=><button key={n} aria-current={page===n?'page':undefined} onClick={()=>{setPage(n);setSelected(1+n*4)}}>{String(2+n*4).padStart(2,'0')}—{String(5+n*4).padStart(2,'0')}</button>)}</nav></div></section>
}
export function PackagingSystem(){
 const[flavor,setFlavor]=useState(0),[detail,setDetail]=useState(0);const product=products[flavor],zone=zones[detail];
 return <section className="m531-packaging" style={{'--m531-accent':product.color} as CSSProperties} aria-labelledby="m531-packaging-title"><header><span className="m531-folio">04 / PACKAGING SYSTEM</span><span>355 mL / PREMIUM WINE COCKTAILS</span></header><h2 id="m531-packaging-title">Consistency<br/><em>without sameness.</em></h2><div className="m531-package-layout"><figure className="m531-master"><img src={'/assets/mymosa-native/'+product.file+'.webp'} width={flavor===0?406:405} height={1172} alt={'MyMosa '+product.name+' 355 mL can, complete front label.'} loading="lazy"/><figcaption>{product.name}<span>355 mL</span></figcaption></figure><div className="m531-inspection"><nav className="m531-zone-nav" aria-label="Packaging detail">{zones.map((z,i)=><button key={z.id} aria-pressed={detail===i} onClick={()=>setDetail(i)}><small>0{i+1}</small>{z.name}</button>)}</nav><div className="m531-detail" aria-live="polite"><span>{zone.label}</span><div className="m531-crop-field"><img src={'/assets/mymosa-native/details/'+product.file+'-'+zone.id+'.webp'} width={zone.width} height={zone.height} style={{maxWidth:zone.width}} alt={product.name+' packaging detail: '+zone.name+'.'} loading="lazy"/></div><h3>{zone.name}</h3><p>{zone.copy}</p></div></div></div><div className="m531-flavors" role="group" aria-label="Packaging flavor">{products.map((p,i)=><button key={p.file} aria-pressed={flavor===i} onClick={()=>setFlavor(i)}><small>0{i+1}</small>{p.name}<i aria-hidden="true" style={{background:p.color}}/></button>)}</div></section>
}
