import {useRef,useState} from 'react';
const original='';
const links=[['Work','/work'],['How we build','#operating'],['Company Builder','#review-builder'],['Capabilities',original+'/capabilities'],['Studio',original+'/studio']];
const Arrow=()=> <span aria-hidden="true">↗</span>;
export function ReviewHeader(){
 const menu=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null);
 const[open,setOpen]=useState(false);
 function close(){menu.current?.close();setOpen(false);trigger.current?.focus()}
 return <header className="r52-header"><a href="/" className="p-wordmark">DYNASTY WORKS<span>STUDIO</span></a><nav aria-label="Main navigation" className="r52-desktop-nav">{links.map(([name,url])=><a href={url} key={name}>{name}</a>)}</nav><a className="r52-nav-action" href="#review-builder">Start a company <Arrow/></a><button className="r52-menu-trigger" ref={trigger} aria-expanded={open} aria-controls="r52-menu" onClick={()=>{menu.current?.showModal();setOpen(true)}}>Menu <span aria-hidden="true">＋</span></button><dialog ref={menu} id="r52-menu" className="r52-menu" onClose={()=>{setOpen(false);trigger.current?.focus()}}><div><span>Dynasty Works Studio</span><button onClick={close} aria-label="Close navigation">Close ×</button></div><nav aria-label="Mobile navigation">{links.map(([name,url])=><a href={url} key={name} onClick={close}>{name}<Arrow/></a>)}</nav><a className="r51-action" href="#review-builder" onClick={close}>Start a company <Arrow/></a></dialog></header>
}
export function Proof(){return <section className="r52-proof" id="proof" aria-labelledby="proof-title"><span className="r52-folio">05 / THE PROOF</span><h2 id="proof-title">The work is there<br/><em>when you want<br/>the proof.</em></h2><div className="r52-paths"><a className="r52-work-path" href="/work"><span className="r52-path-meta">01 / REAL CASE STUDIES</span><h3>Selected<br/>work.</h3><span className="r52-path-action">Explore selected work <Arrow/></span></a><a className="r52-lab-path" href="/concept-lab"><span className="r52-path-meta">02 / INDEPENDENT CAPABILITY STUDIES</span><h3>Concept Lab</h3><span className="r52-path-action">Enter Concept Lab <Arrow/></span></a></div></section>}
export function Invitation(){return <section className="r52-invitation" id="invitation" aria-labelledby="invitation-title"><div className="r52-invitation-top"><span className="r52-folio">06 / THE INVITATION</span><p>The next company<br/>has not been built yet.</p></div><h2 id="invitation-title">What are<br/><em>we building?</em></h2><div className="r52-invitation-end"><span className="r52-seed" aria-hidden="true"><i/></span><div><a className="r51-action" href="#review-builder">Start a company <span aria-hidden="true">→</span></a><a className="r52-talk" href={original+'/contact'}>Talk to the studio <Arrow/></a></div></div></section>}
export function ReviewFooter(){return <footer className="r52-footer"><div className="r52-footer-identity"><a href="/" className="p-wordmark">DYNASTY WORKS<span>STUDIO</span></a><p>Company creation studio<br/>Ideas become assets.</p></div><nav aria-label="Footer navigation">{links.map(([name,url])=><a href={url} key={name}>{name}</a>)}<a href="#review-builder">Start a company <Arrow/></a></nav><small>© {new Date().getFullYear()} Dynasty Works Studio</small></footer>}
