import {lazy,Suspense,useEffect,useRef,useState,type CSSProperties} from 'react';
import {businessTypes,type BusinessType} from '@/data/company-builder';
import {founderBlueprint} from '@/data/founder-blueprint';
import './v5.css';
const Diagnostic=lazy(()=>import('./Diagnostic'));
const original='https://dynasty-works-studio.ernestyearby.chatgpt.site';
const disciplines=[
 {name:'Strategy',terms:['Audience','Position','Opportunity','Business model'],copy:'Find the opportunity. Give the company a direction.'},
 {name:'Identity',terms:['Naming','Typography','Color','Marks','Language'],copy:'A recognizable voice, expressed as one coherent identity.'},
 {name:'Product',terms:['Architecture','Packaging','Materials','Prototype'],copy:'Turn the idea into something tangible.'},
 {name:'Digital',terms:['Experience','Interface','Automation','Platform'],copy:'Build the experience. Connect the infrastructure.'},
 {name:'Experience',terms:['Physical','Service','Hospitality','Environment'],copy:'Consider every place the company meets a person.'},
 {name:'Market',terms:['Launch','Content','Retail','Distribution','Growth'],copy:'Prepare the company to enter its market.'},
 {name:'Systems',terms:['Operations','Workflows','Automation','Infrastructure'],copy:'Connect information, decisions and approved actions.'}
];
const ranges=[
 ['Company','Positioning / Business model / Naming / Roadmap','start'],
 ['Brand','Identity / Language / Art direction / Packaging','brand'],
 ['Product','Concept / Materials / Packaging / Visualization','build'],
 ['Digital','Websites / Applications / Commerce / Interfaces','build'],
 ['Content','Campaign / Creative direction / Publications','publish'],
 ['Market','Launch / Retail readiness / Distribution preparation','distribute'],
 ['Systems','Workflows / AI integration / Operations / Reporting','grow']
];
const moves=[['Define','Direction','Audience / Position / Company roadmap'],['Build','Form','Identity / Product / Digital infrastructure'],['Launch','Connection','Campaign / Experience / Market readiness'],['Scale','Continuity','Optimization / Operations / New markets']];
function Arrow(){return <span aria-hidden="true">↗</span>}
function Header(){const dialog=useRef<HTMLDialogElement>(null);const button=useRef<HTMLButtonElement>(null);const[open,setOpen]=useState(false);const links=[['Work','/work'],['How we build','#method'],['Company Builder','#builder'],['Capabilities','#range'],['Studio',original+'/studio']];function close(){dialog.current?.close();setOpen(false);button.current?.focus()}return <header className="v5-header"><a href="#arrival" className="v5-wordmark">Dynasty Works<span>Studio</span></a><nav className="v5-desktop-nav" aria-label="Main navigation">{links.map(([name,url])=><a key={name} href={url}>{name}</a>)}</nav><a className="v5-header-start" href="#builder">Start a company <Arrow/></a><button className="v5-menu-button" ref={button} aria-expanded={open} aria-controls="v5-menu" onClick={()=>{dialog.current?.showModal();setOpen(true)}}>Menu <span aria-hidden="true">＋</span></button><dialog id="v5-menu" ref={dialog} className="v5-menu" onClose={()=>setOpen(false)}><div><span className="v5-wordmark">Dynasty Works<span>Studio</span></span><button onClick={close}>Close ×</button></div><nav aria-label="Mobile navigation">{links.map(([name,url],i)=><a key={name} href={url} onClick={close}><small>0{i+1}</small>{name}<Arrow/></a>)}</nav><a href="#builder" className="v5-action" onClick={close}>Start a company <Arrow/></a></dialog></header>}
function Creation({reduced}:{reduced:boolean}){const[phase,setPhase]=useState(0);const[manual,setManual]=useState(false);useEffect(()=>{const pref=matchMedia('(prefers-reduced-motion: reduce)');if(reduced||manual||pref.matches)return;const timers=[1,2,3].map((v)=>setTimeout(()=>setPhase(v),v*650));const stop=()=>timers.forEach(clearTimeout);pref.addEventListener('change',stop);return()=>{stop();pref.removeEventListener('change',stop)}},[manual,reduced]);return <div className="v5-creation" data-phase={phase}><div className="v5-creation-caption"><span aria-live="polite">{['The idea','A direction','A structure','A company'][phase]}</span><button aria-label="Advance company creation signal" onClick={()=>{setManual(true);setPhase((phase+1)%4)}}>{phase===3?'Begin again':'Build on it'} <span aria-hidden="true">→</span></button></div><div className="v5-creation-drawing" aria-hidden="true"><i className="v5-origin"/><i className="v5-creation-rule"/>{['Strategy','Identity','Product','Digital','Market'].map((s,i)=><div key={s} style={{'--i':i} as CSSProperties}><b/><span>{s}</span></div>)}<span className="v5-output">Company</span></div></div>}
function Idea(){const[expanded,setExpanded]=useState(false);const terms=['Audience','Position','Identity','Product','Experience','Market','Operations'];return <section className="v5-idea v5-pad" id="idea" data-expanded={expanded}><div className="v5-idea-heading"><span className="v5-meta">01 / The idea</span><h2>An idea is<br/><em>the beginning.</em></h2></div><div className="v5-idea-spread"><button className="v5-seed" aria-expanded={expanded} aria-controls="idea-relationships" onClick={()=>setExpanded(!expanded)}><i aria-hidden="true"/>One idea.<span aria-hidden="true">{expanded?'−':'＋'}</span></button><div id="idea-relationships" className="v5-idea-terms" aria-hidden={!expanded}>{terms.map((s,i)=><span key={s} style={{'--i':i} as CSSProperties}><small>0{i+1}</small>{s}</span>)}</div></div><p className="v5-idea-conclusion">The system<br/>makes it real.</p></section>}
function System(){const[active,setActive]=useState(0);const tabs=useRef<HTMLDivElement>(null);const d=disciplines[active];function keyboard(e:React.KeyboardEvent){let n=active;if(e.key==='ArrowRight'||e.key==='ArrowDown')n=(active+1)%7;else if(e.key==='ArrowLeft'||e.key==='ArrowUp')n=(active+6)%7;else if(e.key==='Home')n=0;else if(e.key==='End')n=6;else return;e.preventDefault();setActive(n);(tabs.current?.children[n] as HTMLButtonElement).focus()}return <section className="v5-system v5-pad" id="system"><header><span className="v5-meta">02 / The system</span><h2>Build more<br/>than a <em>brand.</em></h2></header><div className="v5-system-layout"><div role="tablist" aria-label="Company disciplines" ref={tabs} onKeyDown={keyboard} className="v5-discipline-index">{disciplines.map((item,i)=><button key={item.name} id={'v5-discipline-'+i} role="tab" tabIndex={i===active?0:-1} aria-selected={i===active} aria-controls="v5-system-field" onClick={()=>setActive(i)}><small>0{i+1}</small>{item.name}<span aria-hidden="true">↗</span></button>)}</div><div id="v5-system-field" className={'v5-system-field system-kind-'+active} role="tabpanel" aria-labelledby={'v5-discipline-'+active} tabIndex={0}><span className="v5-system-number" aria-hidden="true">0{active+1}</span><div className="v5-system-terms" key={active}>{d.terms.map((term,i)=><span key={term} style={{'--i':i} as CSSProperties}><small>{String(i+1).padStart(2,'0')}</small>{term}</span>)}</div><p>{d.copy}</p></div></div><p className="v5-system-foot">We build the system around the idea.</p></section>}
function Build(){const[active,setActive]=useState(0);return <section className="v5-build v5-pad" id="method"><h2 className="v5-sr">How we build</h2><div className="v5-build-heading"><span className="v5-meta">03 / The build</span><p>One idea.<br/>Increasingly complete.</p></div><div className="v5-moves" aria-label="Build sequence">{moves.map(([name],i)=><button key={name} aria-pressed={i===active} aria-controls="v5-build-output" onClick={()=>setActive(i)}><span>0{i+1}</span><strong>{name}</strong><i aria-hidden="true">{i===active?'↘':'→'}</i></button>)}</div><div className="v5-build-output" id="v5-build-output" data-build={active}><div className="v5-build-drawing" aria-hidden="true">{[0,1,2,3].map(i=><div key={i} className={i<=active?'is-built':''}><span>0{i+1}</span>{[0,1,2].map(k=><i key={k}/>)}</div>)}</div><div aria-live="polite"><span className="v5-meta">{moves[active][0]} / {moves[active][1]}</span><p>{moves[active][2]}</p></div></div></section>}
function Builder(){const[state,setState]=useState<'start'|'selection'|'questions'>('start');const[type,setType]=useState<BusinessType>('Consumer Brand');const question=useRef<HTMLHeadingElement>(null);useEffect(()=>{if(state==='selection')question.current?.focus()},[state]);return <section className="v5-builder" id="builder"><header className="v5-pad"><span className="v5-meta">04 / Company Builder</span><h2>Bring us<br/><em>the idea.</em></h2><p>A founder diagnostic.<br/>A company roadmap.</p></header><div className="v5-instrument v5-pad" data-state={state}><div className="v5-instrument-rail"><span>Dynasty Works / Company Builder</span><span>{state==='start'?'Input → Roadmap':state==='selection'?'01 / Starting point':'Diagnostic / Active'}</span></div>{state==='start'?<div className="v5-builder-entry"><p>What does your<br/>idea need next?</p><button className="v5-action" onClick={()=>setState('selection')}>Start your roadmap <Arrow/></button><small>Your answers stay in this browser. Nothing is sent.</small></div>:state==='selection'?<div className="v5-type-selection"><h3 ref={question} tabIndex={-1}>What are<br/>we building?</h3><label htmlFor="v5-company-type">Choose the closest fit</label><select id="v5-company-type" value={type} onChange={e=>setType(e.target.value as BusinessType)}>{businessTypes.map(t=><option key={t}>{t}</option>)}</select><button className="v5-action" onClick={()=>setState('questions')}>Build your roadmap <Arrow/></button><small>An initial roadmap, not a quote.</small></div>:<Suspense fallback={<p className="v5-loading" role="status">Opening your roadmap engine…</p>}><Diagnostic businessType={type} onRestart={()=>setState('selection')}/></Suspense>}<div className="v5-blueprint"><span>Go deeper</span><a href={original+'/founder-blueprint'}>Founder Blueprint <Arrow/></a><p>A strategic engagement.<br/>{founderBlueprint.priceLabel}</p></div></div></section>}
function Range(){const[active,setActive]=useState(0);return <section className="v5-range v5-pad" id="range"><span className="v5-meta">05 / The range</span><h2>Simple to enter.<br/><em>Deep enough</em> to build.</h2><div className="v5-range-layout"><div className="v5-range-index" aria-label="Capability categories">{ranges.map(([name],i)=><button key={name} aria-pressed={i===active} aria-controls="v5-range-detail" onClick={()=>setActive(i)}><span>0{i+1}</span>{name}<i aria-hidden="true">{i===active?'↗':'—'}</i></button>)}</div><div id="v5-range-detail" className="v5-range-detail" aria-live="polite"><span aria-hidden="true">0{active+1}</span><h3>{ranges[active][0]}</h3><ul>{ranges[active][1].split(' / ').map(t=><li key={t}>{t}</li>)}</ul><a href={original+'/capabilities/'+ranges[active][2]}>Explore the capability <Arrow/></a>{active===0&&<small>Formation and trademark work is coordinated with qualified specialists.</small>}{active===6&&<small>Connections and approvals are established before activation.</small>}</div></div></section>}
export default function V5(){const[reduced,setReduced]=useState(false);return <div className="v5" data-reduced={reduced}><a className="v5-skip" href="#v5-main">Skip to content</a><Header/><main id="v5-main"><section className="v5-arrival v5-pad" id="arrival"><div className="v5-arrival-meta"><span>Company creation studio</span><span>DWS / From first move to market</span></div><h1>From <em>idea</em><span>to company.</span></h1><div className="v5-arrival-end"><p>Strategy, identity, product, digital, experience and market — built as one connected system.</p><div><a className="v5-action" href="#builder">Start a company <Arrow/></a><a className="v5-link" href="#method">See how we build ↓</a></div></div><Creation reduced={reduced}/></section><Idea/><System/><Build/><Builder/><Range/><section className="v5-proof v5-pad" id="proof"><span className="v5-meta">06 / Selected work</span><h2>The work is there<br/><em>when you want<br/>the proof.</em></h2><div className="v5-proof-paths"><a href="/work"><small>Real case studies</small><span>Explore selected work <Arrow/></span></a><a href="/concept-lab"><small>Concept studies</small><span>Enter Concept Lab <Arrow/></span></a></div></section><section className="v5-invitation v5-pad" id="invitation"><p>The next company<br/>has not been built yet.</p><h2>What are<br/><em>we building?</em></h2><div><a className="v5-action" href="#builder">Start a company <Arrow/></a><a className="v5-link" href={original+'/contact'}>Talk to the studio <Arrow/></a></div></section></main><footer className="v5-footer v5-pad"><a href="#arrival" className="v5-wordmark">Dynasty Works<span>Studio</span></a><p>Ideas become assets.</p><nav className="v5-legal-nav" aria-label="Legal navigation" style={{display:'inline-flex',gap:'16px'}}><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/contact">Contact</a></nav><button aria-pressed={reduced} onClick={()=>setReduced(!reduced)}>{reduced?'Motion reduced':'Reduce motion'}</button><small>© {new Date().getFullYear()} Dynasty Works Studio</small></footer></div>}
