import {useReducer,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {installMotionTokens} from '../experience/tokens';
import {initial,ledger,reducer,phases} from '../genesis-proof/model';
import {Instrument} from './Instrument';
import {stage,stops} from './geometry';
import './genesis.css';
installMotionTokens();
const titles=[['Every company.','Begins as a signal.'],['An idea.','Takes direction.'],['Recognition.','Before decoration.'],['Identity.','Becomes matter.'],['Form.','Becomes behavior.'],['Every decision.','Has a consequence.'],['Automation prepares.','People authorize.'],['The system.','Meets demand.'],['One company.','One continuous instrument.'],['Everything.','Came from the idea.']];
const notes=['One point. The latent elbow.','Purpose, audience and opportunity give the same origin direction.','One proportion. One rhythm. The inherited edge becomes recognizable.','Surface gains thickness. An edge begins to carry consequence.','Human input meets the inherited channel. The same form now responds.','A finite envelope. Price, cost and capacity govern what the instrument can carry.','Preparation can proceed. Consequence stops at the human interruption.','The same opening now joins internal capacity to external demand.','','Construction subtracts. Recorded decisions remain intact.'];
function Genesis(){
 const [progress,setProgress]=useState(0),[force,setForce]=useState(0),[state,dispatch]=useReducer(reducer,undefined,initial);
 const [intent,setIntent]=useState(false),[load,setLoad]=useState(200),[preparation,setPreparation]=useState(0),[market,setMarket]=useState(false);
 const which=stage(progress),step=stops[which],l=ledger(state),operating=which>=6&&which<=8;
 const ready=which===8||preparation===3;
 const legacyClass=which===0?0:which===1?1:which===3?2:which===8?3:which===9?4:5;
 const returnLabel=progress<87?'Market retracts':progress<88?'System quiets':progress<89?'Economics release':progress<90?'Experience withdraws':progress<92?'Form unfolds':progress<93?'Identity simplifies':progress<96?'The original L':'The original point';
 const status=which===0?'POTENTIAL':which===1?'ORIENTATION':which===3?'PHYSICAL CONSEQUENCE':which===8?phases[state.phase].toUpperCase():which===9?returnLabel.toUpperCase():step.label.toUpperCase();
 const stateNote=which===8?(state.phase===0?(state.held?'Held by you. Nothing crosses.':'One prepared request. Nothing crosses without you.'):state.phase<3?'The human decision is recorded. Validation precedes release.':state.phase<6?'One authorized circulation cycle. Capacity remains committed.':'Carrier recovered. The next proposal inherits its return.'):notes[which];
 const reset=()=>{dispatch({type:'reset'});setIntent(false);setPreparation(0);setMarket(false);};
 const properties={progress,state,force,intent,load,preparation,market};
 return <main className={`genesis-story stage-${legacyClass} intelligence-${which}`} data-progress={progress} data-phase={state.phase} data-stage={which}>
 <header><a href="#story">DWS <span>GENESIS / FULL INTELLIGENCE</span></a><span>B / CONTINUOUS INSTRUMENT</span></header>
 <section className="story" id="story" aria-label="Continuous ten-state Genesis">
 <div className="chapter"><span>{step.id} / {step.label.toUpperCase()}</span><span>ONE ANCESTOR</span></div>
 <h1>{titles[which][0]}<br/><em>{titles[which][1]}</em></h1>
 <Instrument {...properties} mobile={false}/><Instrument {...properties} mobile/>
 <div className="state-note" aria-live="polite" aria-atomic="true"><b>{status}</b><p>{stateNote}</p></div>
 {which===1&&<div className="forces" role="group" aria-label="Directional influences">{['Purpose','Audience','Opportunity'].map((name,i)=><button key={name} aria-pressed={force===i} onClick={()=>setForce(i)}>{name}<span>{['Reuse','Temporary protection','Repeated circulation'][i]}</span></button>)}</div>}
 {which===2&&<div className="identity-proof"><span>184 : 30</span><p>Proportion becomes recognition.<br/>The foot establishes a baseline.<br/>The corner establishes a behavior.</p></div>}
 {which===3&&<div className="form-note"><span>SURFACE / THICKNESS / CHANNEL</span><p>The first capacity to carry.</p></div>}
 {which===4&&<div className="intelligence-controls experience-controls"><span>INPUT / REQUEST 001</span><button className="intent-button" onClick={()=>setIntent(true)} disabled={intent}>{intent?'INTENT RECEIVED':'SEND INTENT'} <i aria-hidden="true">↗</i></button><p role="status">{intent?'The channel acknowledges you. Intent is not authorization.':'Press to send intent into the inherited surface.'}</p></div>}
 {which===5&&<div className="intelligence-controls economics-controls"><div className="economic-proposition"><strong>$40 <i>− $18 = $22</i></strong><span>FEE / VARIABLE COST / CONTRIBUTION</span></div><label htmlFor="planning-load">ILLUSTRATIVE MONTHLY LOAD <output>{load} cycles</output></label><input id="planning-load" type="range" min="0" max="300" step="1" value={load} onChange={e=>setLoad(Number(e.target.value))}/><p role="status">{load===200?'At the operating threshold.':load<200?'Below the operating threshold.':'Above the operating threshold.'} ${(22*load-4400).toLocaleString()} after $4,400 fixed cost.</p><small>200 cycles to threshold / 300 ceiling. Planning assumption only; one live demonstration request.</small></div>}
 {which===6&&<div className="preparation"><span>INHERITED CHANNEL / PREPARATION</span><button disabled={preparation===3} onClick={()=>setPreparation(v=>Math.min(3,v+1))}>{['INGEST REQUEST','CHECK CAPACITY + FUNDING','PREPARE RESERVATION','PREPARED / AWAITING AUTHORITY'][preparation]}</button><p role="status">{['Read Request 001 into the channel.','Route one request. No release.','One slot and $18 supported.','Preparation complete. Memory and audit retain this request.'][preparation]}</p></div>}
 {which===7&&<div className="market-intent"><span>CUSTOMER / CHANNEL / FEEDBACK</span><button disabled={market} onClick={()=>{setMarket(true);setIntent(true);}}>{market?'REQUEST 001 CONNECTED':'RECEIVE REQUEST 001'} <i aria-hidden="true">↙</i></button><p role="status">{state.phase>=7?'Return feedback assigns the recovered carrier to the next proposal.':state.phase>=3?'Authorized service crosses the outer edge.':market?'External demand joins the same reservation. No second request created.':'Open the inherited edge to one external request.'}</p></div>}
 {operating&&<div className="authority"><span>REQUEST 001 / HUMAN AUTHORITY</span><p>{!ready?'Complete preparation before authorization.':state.phase===0?'The fold is interrupted. Only you can join it.':state.phase<7?'One request authorized. No authority transfers to the next.':'Recovered carrier → next preparation. New authority required.'}</p><div><button className="authorize" disabled={!ready||state.authorized} onClick={()=>dispatch({type:'authorize'})}>{state.authorized?'AUTHORIZED':'AUTHORIZE CYCLE'} <i aria-hidden="true">↗</i></button><button disabled={!ready||state.authorized} onClick={()=>dispatch({type:'hold'})}>{state.held?'HELD':'HOLD'}</button><button disabled={!ready||!state.authorized||state.phase>=7} onClick={()=>dispatch({type:'next'})}>Advance cycle →</button></div></div>}
 {which===8&&<div className="capacity"><span>{state.phase>=6?'RECOVERED CAPACITY':'AVAILABLE CAPACITY'}</span><b>{l.available}<small> / 300</small></b><p>{state.phase<3?'1 prepared reservation':state.phase<6?'1 committed to service':'Returned. Available again.'}</p></div>}
 {which===9&&<div className="return-note"><span>{progress>=93?'ORIGIN / 64 : 242':returnLabel.toUpperCase()}</span><p>{progress>=99?'The same point. Begin again.':progress>=93?'The L remains. Continue toward the point.':'Market → System → Economics → Experience → Form → Identity'}</p></div>}
 </section>
 <section className="story-control" aria-label="Founder progression control"><div className="control-meta"><label htmlFor="genesis-progress">CONSTRUCTION</label><output htmlFor="genesis-progress">{progress.toFixed(0)} / 100</output></div><input id="genesis-progress" type="range" min="0" max="100" step=".1" value={progress} onChange={e=>setProgress(Number(e.target.value))} aria-valuetext={`${step.label}, ${progress.toFixed(0)} percent. Transaction ${phases[state.phase]}.`}/><nav aria-label="Genesis states">{stops.map(item=><button key={item.id} aria-current={step.id===item.id?'step':undefined} onClick={()=>setProgress(item.p)}><span>{item.id}</span> {item.label}</button>)}<button onClick={()=>setProgress(100)} aria-label="Return to original point">●</button></nav></section>
 <section className={`story-evidence ${operating?'show-evidence':''}`} aria-label="Recorded transaction" data-testid="ledger"><div><span>RECEIPT</span><strong>${l.receipts*40}</strong></div><div><span>CONTRIBUTION</span><strong>${l.contribution}</strong></div><p data-testid="counts">Reservations {l.reservations} / Releases {l.releases} / Receipts {l.receipts}<small>Inspection never undoes the recorded decision.</small></p></section>
 <footer><span>FICTIONAL OPERATING SCENARIO / FOUNDER PROOF</span><div><button onClick={()=>setProgress(0)}>Return to Signal ↗</button><button onClick={reset}>Reset transaction</button><details><summary>Scenario & decision record</summary><p>One reusable protective carrier. Fee $40; variable fulfillment / inspection cost $18; contribution $22. Fixed monthly cost $4,400. Operating threshold 200 completed cycles/month. Capacity ceiling 300 cycles/month. Initial setup/carrier pool $10,000; illustrative funding $18,000.</p><p>Operating funds $8,000. Cash ${l.cash}; available cash ${l.availableCash}. Capacity is modeled in cycle slots. Geometry expresses constraint, not a quantitative chart. Monthly planning load is a separate assumption and never creates extra transactions.</p><p>Intent: {intent?'received':'not tested'}. Preparation inspection: {preparation}/3. External request: {market?'connected':'not tested'}. Next preparation: {l.nextPreparation}.</p><ol>{state.history.map((entry,i)=><li key={i}>{entry}</li>)}</ol><p>Direct Company entry retains the approved prepared-request demonstration. Other stages inspect its capabilities. Return keeps the decision; Reset transaction deliberately starts a fresh demonstration.</p></details></div></footer>
 </main>;
}
createRoot(document.getElementById('root')!).render(<Genesis/>);
